### ISSUE TITLE
callExtension transfer limit in HiveEXT

### ISSUE THREAD

**Issue by ZNUfisk** [EpochModTeam/DayZ-Epoch#1197]
Cause: The default callExtension transfer limit is 10kbytes on results and 2kbytes on format, this causes severe issues. The transfer limit between HiveEXT and ArmA, particularly on a populated database (say 5000 objects in object_data) lead to a lot of severe and compounding issues. The return  return from callExtension can also be corrupted due to race conditions also as it reads a specified memory pointer, if this happens an unexpected return can crash the loop not matching results can also crash the loop. 

Problem(s): 
* Populated (~5000 objects in object_data) Database taking forever to load 
* Severe Wait for host issues when loading
* Sometimes database simply doesn't load at all and server "spawns" without any objects at all

Reproduce by: Adding 5000 buildables on a map, together with vehicles, vaults, and tents with inventories stacking up. Allow the server to ATTEMPT at loading this data, and running into issues (see cause as to why, and problem(s) as to how).

Solution suggestion: Work around the transfer limitation. It has been done by Z.NU dev team for DayZero 1.2 and can be done in Epoch as well. It would solve great many seemingly "random" issues.

**Comment by Namindu** [comment]
Any news on this issue? I would see this as the #1 thing that needs to be completed. Also marked as high priority.

**Comment by icomrade** [comment]
I'm not sure this is actually the issue at work here. Here's why:

The hive is initialized by child 302 which returns the number of objects and the init key. The executing child 302 also loads all of the objects from the object_data table into an array that is never transferred to SQF.

Once the server has the number of objects that are currently in the DB it can load each object sequentially through SQF using a for loop. To do this the server calls child 302 once for every object in the object_data table and child 302 returns a single object while also removing that object from the array stored in C++ In order for you items to reach the required size to be an issue they would probably need to have more items stored in the inventory field than is currently possible.

So, I wouldn't look at the extension as much as the DB, SQF, or configs, especially since I've been unable to replicate this with a DB of more than 5,000 items (granted they were all empty little-birds and not tons of items filled with gear).

**Comment by icomrade** [comment]
Any issue to the callExtension limit is fixed with: https://github.com/EpochModTeam/DayZ-Epoch/commit/00fa89d08f2020172ac383502233e7aad257f814 Although nothing really points to the extension, see the above post as to why it's extremely unlikely, and there's a specific error for the return being larger than callExtension allows, so you would know definitively.
