### ISSUE TITLE
Server: Object x:y not found (message z)

### ISSUE THREAD

**Issue by rawrerz** [EpochModTeam/DayZ-Epoch#1209]
removeAllItems player; 

Epoch isn't deleting objects off previous skins model on skin change, all I can figure anyway. 

player_humanityMorph.sqf ? player_switchModel.sqf ?

_switchUnit = {
addSwitchableUnit _newUnit;
setPlayable _newUnit;
selectPlayer _newUnit;
removeAllWeapons _oldUnit;
{_oldUnit removeMagazine _x;} forEach magazines _oldUnit;
deleteVehicle _oldUnit;
if(_currentWpn != "") then {_newUnit selectWeapon _currentWpn;};
};

Backpack and everything need to be removed, I am not quite sure what else but it looks like 4 different items type 89/91/99/124

**Comment by ebaydayz** [comment]
It is not clear exactly what these messages refer to because they are so ambiguous and poorly documented. One of the only useful wiki pages on the RPT is:
https://community.bistudio.com/wiki/arma.RPT#Client:_Object_2:9_.28type_UpdatePositionMan.29_not_found.

We have fully updated to DayZ 1.8.7 base now, but I've noticed these messages on both vanilla and Epoch. If you find any definite solutions for specific ones I recommend submitting a pull/issue to the vanilla DayZ Git and it will be applied here as well.
