### ISSUE TITLE
Adding visible Area Maintain markers?

### ISSUE THREAD

**Issue by Markokil321** [EpochModTeam/DayZ-Epoch#1215]
Hello,

Just a small suggestion.
Would you consider adding some sort of radius marker visible in game when players press "Maintain Area Preview" on their plotpole. So that they can see WHAT parts are in range added to the NUMBER of parts. Would be helpful for large bases, where one "maintenance" may not be enough to maintain the whole base.

And then make the radius size change depending on the size you have your plotpoles set to with: DZE_PlotPole 			= [45,45]; 

Thanks and keep up the great work!

**Comment by seb3sec** [comment]
Any idea on how to deactivate these markers? My prototype uses these semi transparent sphere objects and puts them as a circle around the area (+ some in the air). I also only spawn them local to save performance (200+ spheres depending on the parameters) 

- remove the markers after x seconds / but: maybe the player hasn't reached the position to check if something is in range
- remove by option at plotpole / but: a bit too much adjustments in the code for this little feature 
- any better idea?

**Comment by hogscraper** [comment]
https://github.com/RimBlock This is the person that made Plot for Life. It has some interesting code that deals with the markers that spawn and allows for respawning them later.

**Comment by seb3sec** [comment]
I know about this feature, but there are two things:
- the default markers have a hitbox which may cause damage to vehicles
- the maintain radius is 20m more than the plot pole radius

**Comment by RimBlock** [comment]
Would be very easy to amend the A Plot for Life code for plot markers to satisfy this requirement.  It would also be very easy to change the marker to whatever someone wanted... could even setup the marker object classname in the variables.sqf so people can choose their own.

F3CUK put in a pull request to make it local to the client but has since removed the pull request.  I will see if he is willing to push it through again.  This would also resolve the issues of one person turning them on and another turning them off causing on / off sync options issues sometimes.

**Comment by Namindu** [comment]
From what i read plot pole for life has be integrated. So shouldn't this be marked as complete?

**Comment by oiad** [comment]
There is a plot markers option for when we have plot management turned on but not for without it, that is easy to add, however. I'll submit a pull request

**Comment by oiad** [comment]
@icomrade This has now been commited a while ago by @ebaydayz, this thread can be closed if you like.
