### ISSUE TITLE
Combine Ammo ACP/m1911

### ISSUE THREAD

**Issue by Terrien** [EpochModTeam/DayZ-Epoch#1313]
Combie Ammo for the handgun still buggy. (Revolver / m1911 handgun)
Combined ACP (6 rouns) into m1911 mags (2 Mags/clips)
Drove my car until i crashed it.. When i got out the both had reverted back into acp Ammo.
No shots fired, Ammo is full , Cannot combine back into m1911 even tho mags are still full.

**Comment by ebaydayz** [comment]
@icomrade - Testing with your two new commits I still get the problem described by @Markokil321.

Right clicking on revolver rounds and selecting "Combine for M1911" exits with  "Combine ammo failed you need at least 85% capacity to fill a mag" even though both revolver rounds are full. Right clicking on an M1911 mag also gives me the option to "Combine for Revolver", but that exits with the same message.

**Comment by ebaydayz** [comment]
@icomrade - Never mind, updating to the latest player_reloadMags file from DayZ Mod fixed it. I only needed to add the r_action_count variable, otherwise they are 100% compatible. 

Tested and confirmed working with M1911, revolver, wooden arrow, quiver and shot gun rounds.

https://github.com/EpochModTeam/DayZ-Epoch/commit/9d1185409c5730382231ba934932a2b9c0b7dc36

**Comment by icomrade** [comment]
I was trying to figure out why it wasn't working because I tested it before I committed "math is hard" and that shouldn't have broken it. The DayZ vanilla system is much better anyway. r_action_count =  r_action_count + 1; goes in the configs when player_reloadMagazine is called. in DayZ it's used to prevent duping by clicking the ui action quickly.

I'm in the process of updating the configs to 1.8.7 but I haven't gotten to CfgMagazines yet. I'll merge the updated cfgMagazines in when I'm done.
