### ISSUE TITLE
Disable gear menu whilst a safe is being locked.  Safe dupe suggested fix.

### ISSUE THREAD

**Issue by RimBlock** [EpochModTeam/DayZ-Epoch#1341]
Can we have a check onload for RcsDisplayGear.hpp to close the gear menu (display 106) if there is a safe locking within gear range.

This should prevent the safe dupe as the gear menu cannot be opened (or is auto closed) whilst the safe is being locked.

**Comment by ebaydayz** [comment]
Due to the new way safe gear is handled this is no longer necessary. We tested to confirm.

There is no longer a delay between the cargo being recorded and the safe being deleted like their was with the old global setVariable method. Both are performed on the server now:
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_server/compile/server_handleSafeGear.sqf
