### ISSUE TITLE
diag_log

### ISSUE THREAD

**Issue by Namindu** [EpochModTeam/DayZ-Epoch#1356]
Regarding this: http://epochmod.com/forum/index.php?/topic/13259-serverpbo-suggestion/#entry94872

We could make a globe variable, that can be set on or off. That way people can stop complain about it? Would be pretty simple to do.

Just a variable like "Dayz_diag_debug = [True/False]". Then do "if" commands for the "diag_log" listed in server files.

**Comment by icomrade** [comment]
2 ways you can do this. First, by uncommenting or adding lines in these 2 functions found in server_functions.sqf (this is 1.0.6 code, not sure if 1.0.5.x is the same code, although the diag_log lines will be mostly if not exactly the same).
```
server_hiveWrite = {
	private "_data";
	//diag_log ("ATTEMPT WRITE: " + _this);
	_data = "HiveExt" callExtension _this;
	//diag_log ("WRITE: " +str(_data));
};

server_hiveReadWrite = {
	private ["_key","_resultArray","_data"];
	_key = _this;
	//diag_log ("ATTEMPT READ/WRITE: " + _key);
	_data = "HiveExt" callExtension _key;
	//diag_log ("READ/WRITE: " +str(_data));
	_resultArray = call compile format ["%1",_data];
	_resultArray
};
```

Second, you can also use the [Logger] category in hiveExt.ini to enable/disable logging and view calls and responses in HiveExt.log. If your server doesn't have this category copy and paste the text below into your hiveExt.ini and uncomment the Level line and change it to your desired log level.
```
[Logger]
;Possible values: trace, debug, information, notice, warning, error, critical, fatal, none
;They are sorted by importance (low to high), with trace being the most verbose, and none would turn off logging
;This controls both the file output level, and the console output level
;Level = information

;Uncomment this option to override the logging level for the console only
;The specified level can only be higher than the global one, setting lower values will have no effect
;So for example, if you want to have information-level logs in your file, but only warning-level and higher in your console
;You would uncomment this option and set it to warning
;Leaving it commented out means there's no special level for the console, so it will just use the global one
;ConsoleLevel = information

;By default, the HiveExt console log output will go to the Arma2 server window, with colour highlighing by importance
;If you want to use the old style, separate windows console window for the HiveExt log output, set this option to true
;SeparateConsole = false
```

Closing because the tools discussed in this issue already exist in 1.0.5 Hive and can be enabled very easily by using HiveExt.ini and/or adding or uncommenting diag_log lines in server.pbo.
