### ISSUE TITLE
.RPT Errors

### ISSUE THREAD

**Issue by Markokil321** [EpochModTeam/DayZ-Epoch#1399]
Don't think anything has actually been broken, but i have been getting these errors since the 1.0.5.1 update. Random occurrences.

//\/\/\/\/\\

20:35:39 Error in expression <;
_recompile = (count _this) > 0;
if (BIS_fnc_init && !_recompile) exitwith {t>
20:35:39   Error position: <BIS_fnc_init && !_recompile) exitwith {t>
20:35:39   Error Undefined variable in expression: bis_fnc_init
20:35:39 File ca\Modules\Functions\init.sqf, line 28

//\/\/\/\\/

20:43:04 Error in expression < = ((_this select 1) select 1);

_agent enableSimulation _control;
};

if (isSe>
20:43:04   Error position: <enableSimulation _control;
};

if (isSe>
20:43:04   Error Generic error in expression
20:43:04 File z\addons\dayz_code\init\publicEH.sqf, line 35

//\/\/\/\/\

21:50:00 Error in expression <ate _attacker;
diag_log ("Weapon: "+str(_weapon));
if (_weapon select 0 == "Thro>
21:50:00   Error position: <_weapon));
if (_weapon select 0 == "Thro>
21:50:00   Error Undefined variable in expression: _weapon
21:50:00 File z\addons\dayz_server\compile\fnc_plyrHit.sqf, line 39

**Comment by ebaydayz** [comment]
The first one was fixed with the [recent A2OA core patch](https://forums.bistudio.com/topic/186695-a2a2oa-patch-18122015/):
<pre>- Fixed BIS_fnc_init error of BIS Function Module</pre>

The last one was fixed here #1420, although that file still needs some work.

The second one can happen if you are using a zombie delete script such as a safezone or the infistar admin one. The agent is deleted right after it spawns, so at the bottom of zombie_generate.sqf _agent is a null object.
