### ISSUE TITLE
Keyless Entry

### ISSUE THREAD

**Issue by Namindu** [EpochModTeam/DayZ-Epoch#1447]
Ok, so new vehicles have the ability to use "keyless entry". Basically you enter a combo on the driver side door and it unlocks the vehicle. 

https://www.youtube.com/watch?v=Vyf1-cuWW1o

It would require a GUI, and this would be on the "New vehicles" (Suvs, and anything else that would fit in). This would allow the user who "lost their keys" still able to use the vehicle.
And at the same time have the ability to get quick access to a vehicle without the need of a key.

**Comment by icomrade** [comment]
I'm going to close this because keys offer an opportunity to steal a vehicle, whereas changing the system to keyless entry would completely change this part of game play. I think if you wan't to implement this in your own server then feel free to, but I don't think supporting this officially would be beneficial or consistent with the game player experience provided or desired.
