### ISSUE TITLE
Suggestion - Molotov; One Cocktail to rule them all 

### ISSUE THREAD

**Issue by Psykofloyd** [EpochModTeam/DayZ-Epoch#1448]
I wonder if that's possible to add Molotov cocktail crafted with empty whiskey bottle, burlap and box of matchs.
There is a script in armaholic that could be a good start but it's for ARMA  :
http://www.armaholic.com/page.php?id=4411

I see zombies burning in my dreams i would love for it to be real :)

Thanks for your great job :+1:

**Comment by icomrade** [comment]
The sound effects are hilarious but judging by the comments it's broken. Although the idea of Molotovs is ArmA is cool it seems more like a novelty than a serious, tested and working addon. Closing because I don't think anyone here is going to seek out permission from the addon owner and go about fixing it to a level that is suitable for release.
