### ISSUE TITLE
Modular buildings decaying prematurely

### ISSUE THREAD

**Issue by Jmaster9999** [EpochModTeam/DayZ-Epoch#1463]
I've been working on a Overpoch Taviana server and I've run into a problem. Bases on the server decay after 7 days even though the decay time is set for 3 weeks. There is also no warning to the decay, and no way to maintain the base components. On server restart the base parts are deleted. 
Any help would be appreciated as this is an urgent issue for our server.

**Comment by icomrade** [comment]
I fail to see an issue in the hive with cleanup, I would ensure that you have properly configured CleanupPlacedAfterDays in your hive config and that you do not have a scheduled procedure running  that conflicts with that value. For reference here is the statement in the HiveExt that is executed, the CleanupPlacedAfterDays is defaulted to 6 days if your value is not configured.

Note: The commonSql  string is appended to a DELETE statement and is then executed on the DB.

```
		string commonSql = "FROM `"+_objTableName+"` WHERE `Instance` = " + lexical_cast<string>(serverId) +
			" AND `ObjectUID` <> 0 AND `CharacterID` <> 0" +
			" AND `Datestamp` < DATE_SUB(CURRENT_TIMESTAMP, INTERVAL "+lexical_cast<string>(_cleanupPlacedDays)+" DAY)" +
			" AND ( (`Inventory` IS NULL) OR (`Inventory` = '[]') )";
````

I'm going to leave this open for now so if anyone has more info regarding this issue they can add it, otherwise I will eventually close it.

**Comment by ndavalos** [comment]
I don't think hive delete is the problem honestly, the main problem with maintenance/decay is people maintaining right before server restart (like within 5-10 minutes). Since the server maintain code updates objects 1 by 1, it sometimes does not actually update all the objects depending on server load. This has been the case 99% of the time when it occurs. If the maintenance would do it in batches of objectids (maybe 100 at a time) it would significantly reduce the chance of maintenance not updating all objects. You would want to just pass in a list of object ids and an update statement where objectid in (<list>). It will also take some load off both mysql and the server.

**Comment by icomrade** [comment]
Should be fixed with a change I made a while ago, but I am too lazy to go back and find it to reference.
