### ISSUE TITLE
Safes are still losing contents

### ISSUE THREAD

**Issue by justchil** [EpochModTeam/DayZ-Epoch#1503]
I've applied all the fixes posted by ebay (forEach replacements).  For almost a week I didn't get complaints but once again the problem is back.  The last time I investigated it I came up with the same details.

9:22pm Player1 puts items into safe:

[[["M32_EP1"],[1]],[["ItemBriefcase100oz","6Rnd_HE_M203","ItemObsidian","ItemSodaRbull","ItemRuby","ItemBriefcase90oz","ItemBriefcaseEmpty","ItemBriefcaseS80oz"],[44,3,3,1,1,1,2,1]],[[],[]]]

I confirmed that he put all of these items into the safe with addmagazinecargo.log.  I didn't confirm if he put the weapon in there but it remains there now.  I also confirmed with my database backups.

At 9:59pm Player1 unlocks safe and finds all items missing and submits a ticket for help.  

I have backups at 9:50 and 10:05 (15min) and I can confirm that the items are indeed missing during this period.

[[["M32_EP1"],[1]],[[],[]],[[],[]]]

There was a restart at 9:30pm EST which is 8 minutes after Player1 placed items in the safe and they were there afterwards.  I don't know what other information I can provide.  There are other server ops with the same problem but I guess most just replace gear and move on.

I have just turned hive.log back down to 'notice' after almost a week of no problems.  If trace logs would help any I can turn it back up to that level and wait for it to happen again.  

===========================

From what I can tell it happened when he unlocked the safe.

**Comment by ReDBaroN1** [comment]
We're getting this happen as well. Sometimes just magazines emptied back to 200 free slots and sometimes weapons as well.
But, as justchil mentioned this happens intermittently but often. Sometimes weekly, sometimes daily.

Did anyone get anywhere towards fixing the issue?

**Comment by ebaydayz** [comment]
With https://github.com/EpochModTeam/DayZ-Epoch/commit/726e4e0c223b7bf10d27b95a8113987cedde3d39 and https://github.com/EpochModTeam/DayZ-Epoch/pull/1467 this should be fixed now. Also https://github.com/EpochModTeam/DayZ-Epoch/pull/1641 fixed handling of strings longer than 2048 characters, which probably happened with safe inventories sometimes. 

My testing method was as follows:
1. Place two safes and two lockboxes.
2. Fill one safe and one lock box to 100% capacity (full bags, mags and weapons).
3. Partially fill the other safe and lock box.
4. Lock all safes and lockboxes.
5. Copy all four object_data entries from database and verify they are correct.
6. Log out normally.
7. Restart the server.
8. Log in, unlock all safes and lockboxes and verify contents are correct.
9. Refresh database and verify contents are still unchanged.
10. Repeat steps 4-10.

I also tested removing gear and adding different gear between restarts. I even tested leaving the safes unlocked before a restart. Neither made a difference.

If you find this bug still exists after applying the above commits then we need exact steps to reproduce it on a stock server. Otherwise we have no way to confirm it is not some other mod on the server at fault.
