### ISSUE TITLE
Duplicate ObjectUID on trader purchased vehicles.

### ISSUE THREAD

**Issue by justchil** [EpochModTeam/DayZ-Epoch#1504]
I've been getting reports of disappearing vehicles.  After investigating I found out  that another vehicle with the same ObjectUID was purchased from a trader exactly when the first vehicle disappeared.

	Line 4314:  5:18:58 "HIVE: WRITE: "CHILD:308:11:GAZ_Vodnik_MedEvac:0:1401:[32,[11455.5,11341.2,0]]:[]:[]:1:11455511341201792:""
	Line 4319:  5:19:07 "HIVE: WRITE: "CHILD:388:11455511341201792:""
	Line 4321:  5:19:13 "PUBLISH: B 2-1-D:1 (Player1) REMOTE Bought GAZ_Vodnik_MedEvac with ID "11455511341201792""

	
	Line 21577: 23:45:56 "HIVE: WRITE: "CHILD:308:11:TT650_Ins:0:12047:[237,[11455.5,11341.2,0]]:[]:[]:1:11455511341201792:""
	Line 21580: 23:46:11 "HIVE: WRITE: "CHILD:388:11455511341201792:""
	Line 21582: 23:46:11 "PUBLISH: B 1-3-G:1 (Player2) REMOTE Bought TT650_Ins with ID "11455511341201792""

Both were several restarts apart.  Both objects still exist in the database.

Screenshot of db rows: http://prntscr.com/4a89ql

**Comment by ebaydayz** [comment]
As mentioned in #1602 this problem is more severe on modded servers that store UID lists in some object inventory fields. In that case if the class swaps it can cause sever_monitor to error out and stop the server from loading. On a stock server the worst it will do is swap class, delete or wipe the inventory of an object (car --> wall, etc.).

Thanks to [@RimBlock's excellent explanation.](http://epochmod.com/forum/index.php?/topic/30634-objectuid-calculation-and-how-to-improve-it/) I will use his idea to store the current highest objectUID on the server in a global variable. It will start with the highest objectUID in the database at restart, then increment by +1 every time a new objectUID is generated.

**Comment by ebaydayz** [comment]
I used @RimBlock's idea and made an array to store all the objectUIDs in. Unfortunately, it looks like the HIVE calls at server startup do not return the objectUIDs, only the objectIDs. I needed to recalculate the objectUID for each object at start up using the worldspace. This is probably not the most efficient solution, but it's definitely faster than doing a separate hive call for each object. If someone knows a better way please let me know.

I tested by logging the array and verifying its objectUIDs matched the ones in the database across restarts. There were also no duplicates. It seems to work okay. My only concern is the array will be very large on servers with thousands of objects. The largest arrays I've dealt with in SQF were about 800 elements long. I don't know if it can handle searching one that is thousands long at decent speeds.

If someone with a busy server is willing to test this it would be greatly appreciated. It is harmless to add regardless of which mods you are running. The only effect it will have is ensuring you have no more duplicate objectUIDs going forward. I need to make sure it can handle several thousand objects. If it can't the main symptom will be vehicles purchased from traders spawning very slowly or not at all (although that is already a problem in 1.0.5.1). You can also find these comments in server_monitor.sqf and add the diag_log line below them:
<pre>// # NOW SPAWN OBJECTS #
	diag_log format["SM SPAWN OBJECTS START: %1",diag_tickTime];</pre>
<pre>// # END SPAWN OBJECTS #
	diag_log format["SM SPAWN OBJECTS FINISH: %1",diag_tickTime];</pre>
Subtract the start from the finish time to see how long it takes the server to load. Do it with both your normal server and with this change applied. That will tell us the impact recalculating the objectUIDs for every object at startup has. It consistently took ~20s for 300 objects on my test server with a 7200rpm HDD. It also took 20s without this change, so the difference is negligible for me.

If you are still alive @RimBlock @Windmolders @justchil @maca134  I would love your input on my solution. Submitted as a pull request so hopefully some more people will notice and review it:

https://github.com/EpochModTeam/DayZ-Epoch/pull/1675

Thanks

**Comment by ebaydayz** [comment]
I tested some large arrays. The "in" command is very fast at searching strings. This is the script I used:
<pre>bigArray = [];
bigArray resize 100000;
{
	bigArray set [_forEachIndex,(str (random 99999999999999999))];
} forEach bigArray;

_startTime = diag_tickTime;
_result = "14665911931529827" in bigArray;
_total = diag_tickTime - _startTime;
systemChat format["Searching array took %1 seconds",_total];</pre>

Searching anything less than 2,000 results in 0 seconds. 
Searching 10,000 results in 0.000976563 seconds.
Searching 30,000 results in 0.0319824 seconds.
Searching 100,000 results in 0.0500488 seconds.

So it seems it can handle arrays that large and the difference in searching speed is fractions of a second.

I'm going to go ahead and commit this change. If anyone finds issues with it or thinks of a better way we can easily remove it later. It is only twelve lines of code.

Final version committed here: https://github.com/EpochModTeam/DayZ-Epoch/commit/ff4a227a1de6f4235122d5220b1f5d68430ab037

**Comment by icomrade** [comment]
The code looks good. The only thing I'd worry about is in a server running at 10 or <10 fps multiple searches of an extremely large array become very time consuming.

A better way to do this instead of using `in` might be to use `find` like so

```
_keyDetector = currentObjectUIDs find _key;
_next = 0;
_exit = false;
if (_keyDetector < 0) then {
	currentObjectUIDs set [count currentObjectUIDs,_key];
} else {
	while {!_exit} do {
		_last = parseNumber (currentObjectUIDs select _keyDetector);
		_next = parseNumber (currentObjectUIDs select (_keyDetector + 1));
		if ((_last + 1) < _next) then {
			keyStartNumber = keyStartNumber + 1;
			_key = str keyStartNumber;
			currentObjectUIDs set [count currentObjectUIDs,_key];
			_exit = true;
		} else {
			_keyDetector = _keyDetector + 1;
		};
	};
};
```

I have no idea how intensive `find` is in comparison to `in` but I have a feeling running find once is more efficient than potentially running `in` multiple times. Other than that, nice fix.

**Comment by ebaydayz** [comment]
I ran the same benchmark with find vs in using the editor. Here are the results:
<pre>in:
"Searching array with 100000 elements took 0.0159912 seconds"
"Searching array with 200000 elements took 0.0209961 seconds"
"Searching array with 300000 elements took 0.0279541 seconds"
"Searching array with 400000 elements took 0.0350342 seconds"
"Searching array with 500000 elements took 0.0419922 seconds"

find:
"Searching array with 100000 elements took 0.0148926 seconds"
"Searching array with 200000 elements took 0.0209961 seconds"
"Searching array with 300000 elements took 0.0289307 seconds"
"Searching array with 400000 elements took 0.0350342 seconds"
"Searching array with 500000 elements took 0.0410156 seconds"</pre>

I ran a second trial and the results were about the same, sometimes in was slightly faster, sometimes find, but usually they were the same. So it looks like there is no significant difference for searching huge arrays of strings.

A duplicate objectUID is a rare occurrence, so something like 98% of the time it will only be searching the array once. The chance that a second consecutive duplicate objectUID occurs is even smaller, a third even smaller and so on. I'm just going to leave it as is since it's simpler, but thanks for the review.

**Comment by Evocation** [comment]
thx for sharing (y) :)

**Comment by SKO85** [comment]
I have the following solution whish I use for my Epoch 1.0.5.1 server. I even use vector building which is modified for the dayz_objectUID2 function. Try the following if you still have issues with UID's.

**server_monitor.sqf:**
Find code:
```
_totalvehicles = 0;
{
_x select 1;
_x select 2;
_ownerID = 		_x select 3;
_worldspace = 	_x select 4;
_inventory =	_x select 5;
_hitPoints =	_x select 6;
_fuel =			_x select 7;
_damage = 		_x select 8;
```

After `_damage = _x select 8;` place the following:
`if (_type in dayz_allowedObjects) then { _worldspace call dayz_objectUID2; } else { _worldspace call dayz_objectUID3; };`

**server_functions.sqf**:

1. Add `currentObjectUIDs = [];` before `dayz_objectUID = { ... }`
2. Change **private** declaration of dayz_objectUID2 and dayz_objectUID3 to `private["_position","_dir","_key", "_exit", "_keyDetector"];`
3. Before `_key`, at the end of both functions (dayz_objectUID2 and dayz_objectUID3) add the following code:
```

// Check duplicates.
_exit = false;
while {!_exit} do {
        // Check if _key is already defined.
	_keyDetector = currentObjectUIDs find _key;
	if(_keyDetector < 0) then {
                // If not, add it to the list and exit the loop.
		currentObjectUIDs set [count currentObjectUIDs, _key];
		_exit = true;
	}
	else {
               // Key already exists, so add +1 and try again.
		_key = str((parseNumber _key) + 1);
	};
};

```

**Example of dayz_objectUID3**:
```
dayz_objectUID3 = {
	private["_position","_dir","_key", "_exit", "_keyDetector"];
	_dir = _this select 0;
	_key = "";
	_position = _this select 1;
	{
		_x = _x * 10;
		if ( _x < 0 ) then { _x = _x * -10 };
		_key = _key + str(round(_x));
	} count _position;
	_key = _key + str(round(_dir + time));
	
	// Check duplicates.	
	_exit = false;
	while {!_exit} do {
		_keyDetector = currentObjectUIDs find _key;
		if(_keyDetector < 0) then {
			currentObjectUIDs set [count currentObjectUIDs, _key];
			_exit = true;
		}
		else {
			_key = str((parseNumber _key) + 1);
		};
	};	
	_key
};
```
