### ISSUE TITLE
DB: object_data:Hitpoints too short

### ISSUE THREAD

**Issue by ekroemer** [EpochModTeam/DayZ-Epoch#1569]
Hi there,

I just realized why from time to time the hive.log says it couldn't spawn Merlin_DZE: this chopper has so many glass parts that the entry in Hitpoints exceeds the 512 character boundary and ends up with a malformed statement, e.g.:

[["NEtrup",0.183],["motor",0.49],["elektronika",0.554],["mala vrtule",0.587],["velka vrtule",0.263],["glass1",0.508],["glass2",0.418],["glass3",0.134],["glass4",0.584],["glass5",0.08],["glass6",0.104],["glass7",0.127],["glass8",0.08],["glass9",0.285],["glass10",0.252],["glass11",0.043],["glass12",0.538],["glass13",0.407],["glass14",0.388],["glass15",0.193],["glass16",0.308],["glass17",0.018],["glass18",0.445],["glass19",0.294],["glass20",0.172],["munice",0.503],["sklo predni P",0.334],["sklo predni L",0.017

Short of making the field longer and change all calls in the hive.dll I cannot think of another solution.

**Comment by ebaydayz** [comment]
Rounding the damage values to one decimal place would reduce it by 56 characters or more. I'm not sure if that would be enough though. It depends which other vehicles this affects. 

From my testing this happens rarely because it requires nearly every single part to be damaged. Here is my badly damaged Merlin I intentionally landed hard and shot out all the glass on:
<pre>[["NEtrup",1],["motor",1],["elektronika",0.806],["mala vrtule",0.049],["velka vrtule",1],["glass1",1],["glass2",0.735],["glass3",1],["glass4",1],["glass5",1],["glass6",0.1],["glass7",0.043],["glass8",0.336],["glass9",0.153],["glass10",0.315],["glass11",0.11],["glass12",0.224],["glass13",0.043],["glass14",0.044],["glass15",0.332],["glass16",0.475],["glass17",1],["glass18",1],["glass19",0.495],["glass20",1]]</pre>

That is only 409 characters, so it is a rare occurrence indeed. I will investigate the rounding option.

**Comment by icomrade** [comment]
Needs testing but I don't see any reason the change wouldn't fix this issue. I'll be able to test this later but if someone can do it quicker verify the fix and reply or close the issue.

**Comment by icomrade** [comment]
Confirming this is fixed, hive saved and read all damaged parts on the Merlin, 517 characters total.

```[["NEtrup",0.503],["motor",0.503],["elektronika",0.503],["mala vrtule",0.503],["velka vrtule",0.503],["glass1",0.503],["glass2",0.503],["glass3",0.503],["glass4",0.503],["glass5",0.503],["glass6",0.503],["glass7",0.503],["glass8",0.503],["glass9",0.503],["glass10",0.503],["glass11",0.503],["glass12",0.503],["glass13",0.503],["glass14",0.503],["glass15",0.503],["glass16",0.503],["glass17",0.503],["glass18",0.503],["glass19",0.503],["glass20",0.503],["munice",0.503],["sklo predni P",0.503],["sklo predni L",0.503]]```
