### ISSUE TITLE
Request: Different type of combination lock for wood doors.

### ISSUE THREAD

**Issue by arcooke** [EpochModTeam/DayZ-Epoch#1584]
Combination locks are extremely expensive and extremely rare.  Because wood doors are so easy to break, it's pointless to put a lock on.  You are almost guaranteed it will be destroyed in a matter of days, along with your expensive combination lock.  I suggest a different type of lock that's cheaper and only works on wood doors.  

This would be helpful for new players who are already overwhelmed with expenses trying to get their first base established.

**Comment by ebaydayz** [comment]
As mentioned by @outseeker- this should no longer be an issue now that plot management and plot for life are integrated. You can add your friends to the plot to grant them access to remove walls. Since you keep ownership of everything after death you will be able to remove walls at will enabling them to act like doors.

It would make things needlessly complicated to require different locks for wood and cinder. Also the combo lock price and rarity can be changed by admins in their loot tables and trader configs.
