### ISSUE TITLE
Request: re-balance cargo space

### ISSUE THREAD

**Issue by seb3sec** [EpochModTeam/DayZ-Epoch#1588]
I'd like to see a set of better balanced car configs for Epoch. Right now the Armored SUV MG is completely OP and theres absolutely no reason to use a different car. Everyone who can afford a Armored SUV is driving one. (I know, ofther cars like Vodnik have better armor). 

There are a lot of nice cars (HMMVW, LandRover, Vodnik) but they only have few cargo slots. In my opinion it would make much more sense to add some kind of classes, so if you choose a car you actually have to decide which features are important instead of having an allrounder.

Low cars like Lada, Skoda, Pickups(?), etc.: 50 Items (as it is now)
Mid cars: Pickups(?), normal SUV: 100 Items
High cars: Landrover, HMMVW, SUV Armored, etc.: 150 Items (definitely not as much as a cargo truck!)
Cargo trucks: 200 items (as it is now)

**Comment by AirwavesMan** [comment]
So, I'm currently on the re-balance. I will give you gyus a short review about the new Cargo Space:

Planes:

AN2_DZ
	transportMaxWeapons = 20;
	transportMaxMagazines = 125;
	transportmaxbackpacks = 15;

Helis:

UH60_Base
        transportMaxWeapons = 20;
        transportMaxMagazines = 120;
        transportMaxBackpacks = 5;

UH1Y
  	transportMaxWeapons = 10;
	transportMaxMagazines = 80;
	transportmaxbackpacks = 4;

UH1H
	transportMaxWeapons = 15;
	transportMaxMagazines = 100;
	transportmaxbackpacks = 8;

Mi17_DZ
	transportMaxWeapons = 25;
	transportMaxMagazines = 150;
	transportmaxbackpacks = 10;

Mi17_Civilian
	transportMaxWeapons = 10;
	transportMaxMagazines = 100;
	transportmaxbackpacks = 10;

MH6J_DZ
	transportMaxWeapons = 6;
	transportMaxMagazines = 50;
	transportmaxbackpacks = 3;

AH6J_EP1_DZ	
        transportMaxWeapons = 5;
	transportMaxMagazines = 40;
	transportmaxbackpacks = 3;

AH6X_DZ
	transportMaxWeapons = 4;
	transportMaxMagazines = 40;
	transportmaxbackpacks = 2;

BAF_Merlin_DZE
	transportMaxWeapons = 15;
	transportMaxMagazines = 150;
	transportmaxbackpacks = 5;

CH53_DZE
	transportMaxWeapons = 20;
	transportMaxMagazines = 80;
	transportmaxbackpacks = 15;

CH_47F_EP1
	transportMaxWeapons = 40;
	transportMaxMagazines = 350;
	transportmaxbackpacks = 20;

Cars:

HMMWV_Base
	transportMaxWeapons = 12;
	transportMaxMagazines = 70;
	transportMaxBackpacks = 5;

HMMWV_M998A2_SOV_DES_EP1_DZ/DZE
HMMWV_M1151_M2_DES_Base_EP1_DZ/DZE
HMMWV_M1151_M2_CZ_DES_EP1_DZ/DZE
	transportMaxWeapons = 12;
	transportMaxMagazines = 100;
	transportmaxbackpacks = 8;

GAZ_Vodnik_medivac
       transportMaxWeapons = 10; 
       transportMaxMagazines = 80; 
       transportmaxbackpacks = 10;

GAZ_Vodnik_DZ/DZE
      transportMaxWeapons = 15; 
      transportMaxMagazines = 120; 
      transportmaxbackpacks = 10;

ArmoredSUV
	transportMaxWeapons = 15; Up to 30
	transportMaxMagazines = 150; Up to 300
	transportmaxbackpacks = 10; Up to 15

LandRover_Base
	transportMaxWeapons = 10; 
	transportMaxMagazines = 80; 
	transportmaxbackpacks = 5;

LandRover_Special_CZ_EP1_DZ/DZE
LandRover_MG_TK_EP1_DZ/DZE
	transportMaxWeapons = 10; 
	transportMaxMagazines = 100; 
	transportmaxbackpacks = 8;

Thats what I changed for now. Basically I increased the cargo space for the most vehicles. What do you think?

**Comment by ebaydayz** [comment]
@AirwavesMan - I edited your post to show the differences from current values in bold parenthesis on each line. 

Basically you are suggesting increasing most helis, significantly decreasing ArmoredSUV and slightly increasing Vodnik, LandRover and HMMWV cargo spaces.

I think maybe the vanilla heli and airplane cargos should stay the same. No one is really complaining about them in this issue. Anyone who plays vanilla DayZ mod probably expects them to be their default values, and they are already pretty well balanced. Helis like the UH1H and MH6J have limited cargo for a reason, as I assume they do in real life. They provide a huge advantage of fast transportation over large distances, quick take off and landing, so that should come at a price. The bigger helis are harder to land and maneuver, so it is understandable they have more cargo room as they increase in size. That is especially true for those without guns like the Merlin and Ch53. There is little incentive to fly them otherwise. 

I think some of the added Epoch heli's could use a decrease to be more in line with the vanilla helis. Since we are nerfing the ArmoredSUV cargo a corresponding decrease in the blackhawk cargo will keep their values relatively in line. It would then be unnecessary to change their prices as mentioned in the OP of this issue 

I think the Landrover, Vodnik and HMMWV cargo buffs look good. The Landrovers might do with a little more even, since they do not have the armor that HMMWVs and Vodniks get. Vodniks are pretty OP as far as armor / price ratio, so that is something to consider.

I haven't played in a long time, so let me know if I'm way off or missing anything. Input from others familiar with vehicle balance is appreciated too.

**Comment by AirwavesMan** [comment]
I think we should stay away a bit from vanillia dayz and the real life. Epoch is a building and crafting mod. People like to store items and I don't know one server that has no AI missions or an AI sector running. What I mean by that is, we have much items from missions, from looting, from baseattacks and other events. Epoch needs a better cargo balance and I think the best way is to re balance the vehicle by increasing the most cargo space.
I noticed that the ASUV has too much cargo space and no other ground vehicle or air vehicle has kind of the same cargo space like the ASUV. Most of the time, players drive only with the SUV or ASUV over the map. I want to see different vehicles, the land rover or gunner vodnic for example. It is the same thing with the air vehicles. Often I see the UH1Y or the Merlin on servers. The MI17 or the UH1H is a way to rare I think and the most important point, they all have much less cargo space than the ASUV. You cant even loot a single AI mission or an area with a few barracks, that your heli is out of cargo space. Of course that depends on what kind of server you play but all in all more cargo space is the better way I think.
If it is possible I would recommend that the server admins can decide for their own what amount of cargo the vehicles have. I do not know if it is possible to move the cfgVehicle like the cfgTraders to the mission file or an option in the server files.
Another option for that, I created a new vehicle class with the new cargo space and the server admins can decide what they prefer on their servers.

**Comment by ebaydayz** [comment]
Unfortunately it is not possible to override CfgVehicles in the missionConfigFile because Description.ext does not support CfgVehicles:
https://community.bistudio.com/wiki/Description.ext

The land vehicle changes are in agreement with the original discussion in this issue, so they are all good IMO. 

I see your motivation for wanting to increase heli cargo spaces, but I'm not sure if it is something everyone wants. We can always make a poll on the forums. If a good number of people are in agreement, then it should be fine to go ahead and do it.

**Comment by oiad** [comment]
I like the idea of increased space but it does come at a price, as the OP said, the Armored SUV is pretty op at 400 space.

You have to be pretty careful with the balance that @ebaydayz touched on, some of the choppers have lack of space because they make up for it with fire power etc.

I would be in favour of buffing the space but as long as it was a small margin, maybe 10-20% at the most.

If anything vehicle wise that should be looked at, it's fixing the merlin so it doesn't leak fuel any time a window gets broken, that thing is a leaking timebomb.

**Comment by AirwavesMan** [comment]
Ive added a poll on the forum:

http://epochmod.com/forum/topic/42311-epoch-106-vehicle-cargo-balance/

**Comment by AirwavesMan** [comment]
According to the poll on the forum, we should left alone the re-balance for vehicles or what do you guys think?

**Comment by icomrade** [comment]
I honestly wouldn't touch it. As far as inventory space is concerned I think the different variations of the same vehicle need to have the same cargo space I.E MH6J should have the same space as an AH6J/X same with the MI17 variants, etc.

**Comment by ebaydayz** [comment]
The only thing that really needs a decrease is the Armored SUV. Its cargo values are ridiculous as mentioned in the OP. The non-upgraded version has twice the magazine capacity of a Ural which makes no sense. Some upgraded Ural/MTVR/Kamaz/V3S classes with 400 and 800 magazine capacities could be added and then the Armored SUVs could be swapped with those to work around the SQL issue. 

The other vehicle changes are up for debate.

**Comment by ndavalos** [comment]
Guess I'll just have to deal with a bunch of pissed off people when their asuvs turn into cargo trucks. :(

**Comment by oiad** [comment]
@ndavalos : I see that happening, too. People are used to them being like that

**Comment by icomrade** [comment]
I wouldn't touch any vehicle configs unless it's to fix an inherent issue. Obviously everybody is used to the extended cargo space now, even if it makes no sense it may not be an issue. Just because something can be changed doesn't mean it should be.

**Comment by ebaydayz** [comment]
I know it's not a good work around. You guys know SQL better than me if there is another way.

But if everyone wants to leave it alone you can close this issue with "Won't Fix". Idc either way. I don't play the game anymore tbh, just trying to resolve the open issues.

**Comment by AirwavesMan** [comment]
I think if we leave this topic alone we definitely should not increase the Armored SUV Cargo. I see new servers only with Armored SUVs driving around. 400 should be good but not 800.

**Comment by ndavalos** [comment]
If the upgraded version achieves 400, then nerfing it would be fine, just swap the existing ones for the upgraded class on conversion.

**Comment by ebaydayz** [comment]
The upgraded version is currently 800. Same as it was in 1051:
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/Configs/CfgVehicles/Car/ArmoredSUV.hpp#L472

Default version is 400:
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/Configs/CfgVehicles/Car/ArmoredSUV.hpp#L268

**Comment by ndavalos** [comment]
Yeah, I'm just sayin, if you end up nerfing the cargo capacity, make the upgraded achieve what it currently is now :)

**Comment by AirwavesMan** [comment]
If I remember correctly you had not option to upgrade the ArmoredSUV in 1051 or did I miss something?. If you look in the old files: https://github.com/EpochModTeam/DayZ-Epoch/blob/Release_1.0.5.1/SQF/dayz_code/Configs/CfgVehicles/LAND/ArmoredSUV.hpp

**Comment by ebaydayz** [comment]
You are correct @AirwavesMan, my mistake. 1051 did not have any upgraded version. So we could make the upgraded version 400 and swap that for the current default version in the 106 SQL updates.

@AirwavesMan suggested making the default version 150. That would be 50 less than the Ural, MTVR, Kamaz and V3S. What does everyone think?

**Comment by AirwavesMan** [comment]
I think this is a good idea.

**Comment by ndavalos** [comment]
That's probably the best thing to keep people from flipping their lids, but still making cargo more reasonable.

**Comment by oiad** [comment]
That's a good compromise to be honest. I like it.

On 16 August 2016 9:04:51 AM NZST, ebaydayz <notifications@github.com> wrote:
>You are correct @AirwavesMan, my mistake. 1051 did not have any
>upgraded version. So we could make the upgraded version 400 and swap
>that for the current default version in the 106 SQL updates.
>
>@AirwavesMan suggested making the default version 150. That would be 50
>less than the Ural, MTVR, Kamaz and V3S. What does everyone think?
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/EpochModTeam/DayZ-Epoch/issues/1588#issuecomment-239928834

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ebaydayz** [comment]
ArmoredSUV change applied. The consensus seems to be to leave the other vehicles alone for now.
