### ISSUE TITLE
outhouse toiletpaper dupe

### ISSUE THREAD

**Issue by Markokil321** [EpochModTeam/DayZ-Epoch#1599]
"outhouse_kit"
Right click to place the outhouse, the ghost preview will appear and the outhouse will spawn toilet paper, you take the toilet paper out of the ghost preview then you cancel building. After that just right click to place the outhouse again and repeat the process.

Infinite toilet paper to wipe your fat asses with.
Not really a big deal only thing is i have a trash dealer that takes this kinda shit for really cheap.

**Comment by Windmolders** [comment]
Does outhouses have a inventory space? 
I thought they were defined as buildings.

@Markokil321

**Comment by Windmolders** [comment]
It seems you are correcy
```c++
class OutHouse_DZ: Land_KBud
	{
		armor = 200;
		scope = 2;
		offset[] = {0,2.5,1};
		displayName = "Outhouse";
		vehicleClass = "Fortifications";
		transportMaxMagazines = 4;
		transportMaxWeapons = 4;
		transportMaxBackpacks = 4;
		constructioncount = 2;
		class transportmagazines
		{
			class _xx_ItemTrashToiletpaper
			{
				magazine = "ItemTrashToiletpaper";
				count = 1;
			};
		};
	};
```

**Comment by ebaydayz** [comment]
I don't see any issue with removing toilet paper from the included mags. It isn't used for anything here and can still be found in loot spawns anyway. I checked the other buildables and the outhouse is the only one that spawns with included mags.

Tested and confirmed fixed with https://github.com/EpochModTeam/DayZ-Epoch/commit/81d5976031d7b799bd3359582cb1b32f87b4cae5
