### ISSUE TITLE
"Land_Mil_Barracks" Broken Shadows

### ISSUE THREAD

**Issue by Markokil321** [EpochModTeam/DayZ-Epoch#1601]
The shadows of this building are very broken, i had posted about it on dev.withsix however later realized this is not a standard ArmA issue but something to do with the open model of this building.

Only way to fix is to disable "Shadow Detail", however no-one wants an ugly game... Please fix this it is pretty disgusting to look at!!

Video showing the shadows:  https://www.youtube.com/watch?v=mzY3lliE1i4&list=UUWkSxZK6vl44x8igwfUqNFA

**Comment by icomrade** [comment]
This is fixed in the latest DayZero zero_buildings.pbo, but needs permissions from the DayZero devs and slight modifications to work. the former of which is not possible since the .PBO is protected. Unless @vbawol can ask them for a modified zero_buildings.pbo that would be compatible with Epoch it won't get fixed.

The the new zero_buildings.pbo will throw the following errors, some config tweaks would probably fix these relatively easily.

Warning Message: Addon 'zero_buildings' requires addon 'zero_code'

LODShape::Preload: shape 'zero\objects\dead_soldier_0.p3d' not found
Warning Message: Cannot open object zero\objects\dead_soldier_0.p3d

**Comment by icomrade** [comment]
Will be fixed with 1.0.6.2 and new DayZero enterable buildings addon
