### ISSUE TITLE
Add USEC Bell 206B (Civilian Helicopter) addon

### ISSUE THREAD

**Issue by Psykofloyd** [EpochModTeam/DayZ-Epoch#1607]
Is that possible to put this chopper in the game ?
I think it would look great :)
http://www.armaholic.com/page.php?id=13285

**Comment by ebaydayz** [comment]
The addon was made by Rocket in 2011, but he did not specify a license anywhere. It also has some issues, but was never updated to fix them. See:
https://forums.bistudio.com/topic/109189-usec-bell-206b-civilian-helicopter/#entry1812934
https://forums.bistudio.com/topic/109189-usec-bell-206b-civilian-helicopter/?p=1817873

I can't say because of the licensing issue. It is up to @vbawol

**Comment by ebaydayz** [comment]
Duplicate, already suggested in #1335
