### ISSUE TITLE
[BUG]  exit from  fainting

### ISSUE THREAD

**Issue by skynetdev** [EpochModTeam/DayZ-Epoch#1613]
How to exit from fainting
watch this bug 
http://youtu.be/gZA1e_wKtwM

**Comment by SplenectomY** [comment]
Infistar has this functionality built in by simply blocking all user input while unconscious, and using Infistar or a similar anticheat might be the only way to stop it. However, it might be possible to code in a preventative built into Epoch to keep a player from accessing his or her inventory when unconscious. If I have the time, I will look into this.

**Comment by icomrade** [comment]
I think that user input should be disabled while unconscious. https://github.com/vbawol/DayZ-Epoch/blob/master/SQF/dayz_code/compile/fn_unconscious.sqf#L20

It may be worth moving it inside of the loop but that would ignore any underlying issues. There may be something that is enabling user input (i.e. disableuserinput false;) while still in the unconscious loop.

**Comment by ebaydayz** [comment]
@icomrade - I don't think anything is enabling it, disableUserInput false; is just a touchy command. I find I usually need to run it at least three times in a row before it works. You will notice infistar does the same thing in his scripts. 

Instead of moving it inside the while loop try just making it:
disableUserInput true;disableUserInput true;disableUserInput true;

...

and then at the bottom:
disableUserInput false;disableUserInput false;disableUserInput false;

I know it shouldn't make a difference, but it does. Try it out.

**Comment by Markokil321** [comment]
Changing the current: disableUserInput true; to 3x disableUserInput true; still did not actually disable the user input.

Moving the 3X disableUserInput true; inside the while {r_player_unconscious} loop did disable user input, however it did not enable it back when you woke up from being unconscious.

I had 3X disableUserInput false; in the same place it currently is once in the file.

**Comment by ebaydayz** [comment]
There is some more discussion on this bug here:
http://epochmod.com/forum/index.php?/topic/33045-releasefix-bugs-unconscious-and-invisible-for-ai-humanity-boost/

**Comment by ebaydayz** [comment]
Tested and confirmed fixed for 1.0.6 with https://github.com/EpochModTeam/DayZ-Epoch/commit/441e9fb231a1a2653218eceec17cc9d5ae417fd3. 

The new keyboard event handler is completely disabled while unconscious:
https://github.com/EpochModTeam/DayZ-Epoch/blob/441e9fb231a1a2653218eceec17cc9d5ae417fd3/SQF/dayz_code/compile/fn_unconscious.sqf#L21
