### ISSUE TITLE
 How many of you are compiling the master branch build and testing it?

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/DayZ-Epoch#1623]
I would like to get a test build posted here soon, major problem is that it is likely to be very buggy and unstable. Ideally what we need is for a few skilled guys/gals to build the master branch on there own to test, debug, report issues, and fix bugs. I could provide a test build to start the process but to make certain your proposed fixes actually work its best that everyone involved can build and test on there own. After we release the 1.0.6 dev test build, please report any issues with "1.0.6" in the title so we can better sort the issues.

**Comment by skynetdev** [comment]
I'm always ready for testing, I will test it with real players on my server

**Comment by SplenectomY** [comment]
Already testing as much as I can without requiring an update from my players, so only server side stuff is being tested atm (208.115.238.69:2302 if you'd like to see for yourself). Found some bugs with the new UI and posted a pull request. However, with your blessing, I'll gladly dish out a master branch to my most experienced players and start testing it 100%.

**Comment by ebaydayz** [comment]
I've been packing the changes in dayz_code and using the new pbo on both my client and test server with verifySignatures=0; and the new mission and server pbos. I would gladly test the rest of the client files if you provide a test release. Right now I can't because there are a bunch of pbos missing from the \SQF\ directory on the github.

**Comment by raziel23x** [comment]
+1

**Comment by Barada123** [comment]
I am ready to test version 1.0.6 .
I have your home server machine.

**Comment by Markokil321** [comment]
I'm also willing to help out / test with whatever may be needed.

**Comment by Karakurd** [comment]
+++
I'm ready to test =)
//home server machine

**Comment by Stalke2033** [comment]
I am willing to participate in testing adopted its server there

**Comment by skynetdev** [comment]
@vbawol  any good news?

**Comment by RimBlock** [comment]
Anyone got a pbo build up and running yet.

I am getting cfg errors with 

ErrorMessage: File z\addons\dayz_code\Configs\CfgWeapons\Weapon\Rifle\FN_FAL_ANPVS4_DZE.hpp, line 0: /CfgWeapons.FN_FAL_ANPVS4_DZE: Undefined base class 'FN_FAL_ANPVS4'

and 

ErrorMessage: File z\addons\dayz_code\Configs\CfgMagazines\Planting.hpp, line 83: /CfgMagazines/ItemHempPlant.type: Member already defined.

so far (haven't got past the second one yet).

Could well be my workflow though :-).

Alternatively I can just remove the conflicting CFG items.

If I can get a working build then I have 4 days (Chinese New Year holiday here) to get A Plot for Life integrated.

**Comment by Namindu** [comment]
#1630 should fix it.

**Comment by seb3sec** [comment]
#1631  is a fix, #1630 adds another error for not finding base class for m16a2

**Comment by RimBlock** [comment]
Thanks seb3sec.  Server is now starting so looks like the cfg errors are sorted.

**Comment by RimBlock** [comment]
Ok, client version needs to be updated.  I belive the check is in teh player_monitor.fsm.

Error:
"You are running an incorrect version of DAYZ_CODE, please download this file from dayzepoch.com (You are running version 1.0.5.1 and the server is running version 1.0.5.2)"

The RedRyder pbo seems to have config file issues as well.

I am assuming the prefix of z\addons\redryder for the pbo as that is where all the config.cpp links are pointing although the PBOPREFIX file has a prefix of  \z\addons\redryder.  Setting the prefix with the leading \ causes an error finding config.cpp.

Getting some issues, possibly a pathing / prefix issue for the redryder though.

 2:55:06 Warning Message: No entry 'bin\config.bin/CfgMagazines.RedRyder'.
 2:55:06 Warning Message: No entry '.picture'.
 2:55:06 Warning Message: '/' is not a value
 2:55:06 Warning Message: No entry '.scope'.
 2:55:06 Warning Message: '/' is not a value
 2:55:06 Warning Message: Error: creating magazine RedRyder with scope=private
...

Am also getting the following coming up in both client and server RPT logs.

 2:54:54 Warning Message: No entry 'model.cfg/CfgModels/Default.sections'.
 2:54:54 Warning Message: Size: '/' not an array
 2:54:54 Warning Message: No entry 'model.cfg/CfgModels/Default.sectionsInherit'.
 2:54:54 Warning Message: '/' is not a value

I can still login with these errors but would be worth fixing if anyone has any ideas.

**Comment by Issty** [comment]
When a chainsaw is in players hand the model is bugy.

**Comment by RimBlock** [comment]
Only seen issues related to the RedRyder at the moment from the items I have played with (no chainsaws yet for me).  

Warning: z\addons\redryder\models\redryder.p3d:VIEW_PILOT Error while trying to generate ST for points: 2040, 2042, 2039
Warnings in z\addons\redryder\models\redryder.p3d:VIEW_PILOT
Warning Message: No entry 'model.cfg/CfgModels/redryder.sections'.
Warning Message: Size: '/' not an array
Warning Message: No entry 'model.cfg/CfgModels/redryder.sectionsInherit'.
Warning Message: '/' is not a value
Too detailed shadow lod in z\addons\redryder\models\redryder.p3d (0:1.000000 : 2026) - shadows disabled

Warning Message: Picture z\addons\redryder\textures\bb_magazine_picture.paa not found

Addon redryder (entry 350Rnd_BB_Magazine) not found in the list of active addons.
Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.
redryder

Warning Message: Picture equip\m\m_z\addons\redryder\textures\bb_magazine_picture.paa.paa not found

Slight issues with compass and watch

19:27:19 Warning: z\addons\dayz_communityassets\models\compass.p3d:0 Error while trying to generate ST for points: 863, 853, 852
19:27:21 Warnings in z\addons\dayz_communityassets\models\watch.p3d:shadow(1000)

Have not really seen any other issues after palying from scratch for a few hours today.

Will look at the building system tomorrow.

**Comment by RimBlock** [comment]
Have put a list of issues up on the forums as well at http://epochmod.com/forum/index.php?/topic/32562-dayz-epoch-v106-test-current-bugs-list/ in the hope of more exposure.

After removing the RedRyder code, most of the errors have gone away.

**Comment by arma2WillRobinson** [comment]
RimBlock I believe the reason the RedRyder is causing you so much trouble is because the models on GitHub are binarized. after downloading the redryder file off here, replacing the models with non binarized versions, packing it, dropping it in @Dayz_Epoch/addons and setting up a 1.0.5.1 server with the RedRyder as the spawn weapon, there werent too many errors. There were some that you listed so I'm glad you bought it up. Anyhow #1642 fixes all of the RPT errors I was getting.

**Comment by RimBlock** [comment]
Thanks Will.

So will the new files posted sort out the issues that the binarised files produced as well as the other errors.  Sorry but modelling is not my area of expertise.

I am also not so confident this release is going anywhere again as there seems to be very little dev action since this thread was made high priority.

**Comment by vbawol** [comment]
check my latest push for a test build of the red ryder pbo

**Comment by arma2WillRobinson** [comment]
Awesome thanks for putting up a test pbo Awol! I ran into a small glitch off the bat, the PREFIX was z\addons\dayz_code instead of z\addons\redryder. That was confusing the mission.sqf because "redryder" is declared under addOns[]=, and ultimatley causing the server RPT to loop this:
9:46:31 Missing addons detected:
 9:46:31   redryder
 9:46:31 Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.redryder

**Comment by arma2WillRobinson** [comment]
For testing purposes I created a repository with the just the redryder folder and exact instructions on how to pack and use on an epoch server successfully, or at least it works for me. https://github.com/arma2WillRobinson/Red-Ryder

It also contains a  redryder.pbo that should work. I just need someone besides me to test it.

**Comment by icomrade** [comment]
@arma2WillRobinson You have 2 CFG errors. The first is in your config.cpp, you have no required addons field adjust CFGPatches accordingly, see below the corrected one, you may want to leave requiredaddons empty
```
class CfgPatches
{
	class RedRyder
	{
		units[] = {};
		weapons[] = {"RedRyder"};
		requiredVersion = 1.00000;
		requiredAddons[] = {"dayz_code"}; //or just requiredAddons[] = {};
	};
};
```

Also, in your model.cfg you are missing a semicolon after the } at line 12.

BINARIZE YOUR .P3D FILES! You can leave the unbinarized ones on github in a separate folder but not in the addon. To take some stress off the engine just binarize them.

As for the rest of epoch code, @seb3sec corrected FN_FAL_ANPVS4_DZE.hpp and Planting.hpp

**Comment by arma2WillRobinson** [comment]
I absolutely agree with you on binarizing the .p3d files. In my comment to RimBlock I thought they were already binarized on github so downloading and packing them again with the rest of the folder would cause problems, but I was wrong they are no longer binarized on github, hadn't checked in awhile.

As for the 2 config errors I appreciate you looking the files over, the cfgs will be updated. I didn't add the requiredAddons line initially because I thought that since the addon wasn't dependent on any other it wasn't necessary.

**Comment by RimBlock** [comment]
Thanks VBAwol.  Any rough target date for the 1.0.6 release to work towards or are you waiting for the A2 EOL patch to come out first ?.  Would appreciate any info, so I can also schedule my own workload.

**Comment by Markokil321** [comment]
Hello,

Is there a way the damage to buildables / base objects that gets done by CHAINSAWS is reduced, or possibly prevent them from being used at all on cinder walls/doors.

Currently it is so easy to wreck people's bases with a chainsaw it's stupid, nobody is using them for faster wood cutting anymore. If you have 2 people with a chainsaw and a few cans of fuel they are able to take down several locked cinder doors within a few minutes. This mixed with the fact they can refill chainsaw ammo by re-logging or something similar is making it the #1 troll/grief weapon on many servers.

I plea for a damage reduction (towards buildables/objects) that is done by CHAINSAWS, or implement some sort of chainsaw breaking system if they are used against cinder. I feel this would do a huge amount in balancing the game with today's players.

**Comment by seb3sec** [comment]
I wrote a modification for the player_harvest.sqf which allows to use the sledge hammer for mining iron ore if you're aiming at a specific object (some kind of heap found in mines). It also includes breaking the hammer. Should be easy to modify the code to achieve the same for Cinder_DZE class and chainsaw ammo. But I'm not sure how exploit safe it is.

**Comment by ebaydayz** [comment]
I set up a 1.0.6 test server: <b>37.187.24.192:2312</b>

To join you will need to download this:
https://bitbucket.org/ebay/files/downloads/1.0.6.test.zip

Extract it, put all files in your Arma 2 Operation Arrowhead\@DayZ_Epoch1051\addons\ folder and overwrite the ones in there. You may want to backup the originals first, so you don't need to redownload 1.0.5.1 to join a normal server again.

The pbos in my .zip are created from the current files in vbawol/DayZ-Epoch/SQF/ at the time of this comment. I used @arma2WillRobinson's current redryder pbo from <a href="https://github.com/arma2WillRobinson/Red-Ryder/tree/master/PBO">here</a> because the one in the Test Build/Temp folder did not work. The server is using all the same pbos, the latest dayz_server from /SQF/ and mission from /Server Files/MPMissions/.

It is completely stock on everything. I only changed the default loadout to include a redryder and disabled anti-teleport. I gave everyone the option to teleport and spawn briefcases, so you can quickly test trading and building. You can restart the server by typing <code>#login test106</code> and then
<code>#shutdown</code> in chat. It will automatically come back up. 

I am watching this repository, so I can update it and post a new download link here as more commits are added.

**Comment by RimBlock** [comment]
If you get any takers then let me know.  I will update my repo to bring it bakc in line with this one (plus the A Plot for life stuff) and you can take a copy of that so people can test it out.  If it works fine then I will put in a pull requst to get it merged here.

**Comment by Markokil321** [comment]
I did originally ask awol for a 1.0.6 test build here on github but that doesn't seem to have happened yet.

Either way thanks for this Ebay, i'll hop on as soon as i get my faulty PSU replaced! :)

**Comment by vbawol** [comment]
Seems the EOL patch for A2 is going to be released soon.

Are you ready? https://twitter.com/FoltynD/status/600670419260153856?lang=en

Arma 2: Operation Arrowhead experimental update now out on beta branch! https://twitter.com/FoltynD/status/600680145314140160

**Comment by Gr8z** [comment]
About Time Bohemia ! YAY

**Comment by Windmolders** [comment]
Can i share an opinion on the use of git ( based on my experience at my job).

MASTER:
We use Master branch as a ready branch. Only working stuff is in there. Tested and ready to deploy.

PRODUCTION:
The branch that currently is deployed. On new release this will contain the master from that date.

BETA:
a running branch where everyone can do his tests on. Stuff needs to be tested here before they can be pushed to Master.

Release Branches:
Like u currently have to get easier to older versions. Gets made when a new production is pushed.

Dev branches: 
Well named branches with only 1 issue fixed in it. Better to have alot of branches with small fixes than alot of fixes in 1 big branches.

**Comment by vbawol** [comment]
Makes perfect sense to me @Windmolders, If you would like please set that up here.

**Comment by icomrade** [comment]
Closing because we are compiling test builds and updating the test server fairly regularly and any issues should be posted in #1681 if you wish to test please see the info here https://github.com/EpochModTeam/DayZ-Epoch/tree/master/Test%20Build
