### ISSUE TITLE
Zupas Plot Management, Single Currency, Door Management for 1.0.6

### ISSUE THREAD

**Issue by AirwavesMan** [EpochModTeam/DayZ-Epoch#1685]
Hey folks,

it is amazing to see you working again on the next epoch version. I just aw that you added Zupas Advanced Trading andI think there are 3 more great scripts that should be in the next patch.

Single Currency 3.0 
Plot Management
Door Management 

I think these 3 scripts are almost on every epoch server installed. so why not adding this to the epoch files and for the admins who dont like that just create the DZE = false version. what do you think? is that possible?

**Comment by buck0384** [comment]
I dont think SC should be added as it causes a number of problems many of which public fixes are not around for (duping).

If server owners want single currency they should add it and fix the issues that arise from it themselfs.

This is an EOL Patch for epoch i don't see why it should be included tbh.

**Comment by icomrade** [comment]
I don't know enough about the Single Currency mod to add it, but the other 2 I am okay with. However, I do know that there's a variety of dupes and exploits that exist with the SC mod. More importantly, it completely changes the way a large part of the game, currency, is handled and I don't feel that change such a large aspect of the mod so late in is a great idea. 

I don't feel that plot pole management or door management change the game in such a drastic way, so  I'm open to them (that's not to say everyone is). Ultimately permission from the authors would be needed in order to include their code in the mod. 

I think at this point this patch is a little more than just an EOL patch, there's quite a bit new content in here.

**Comment by Windmolders** [comment]
Indeed, single currency is a big change to put in the core code. + There are still duping issues never addressed by me due to time issues.

You have all my permissions to use any of my code ( the older the more badly they are) to use.

I'm not sure atm but Plot4life (By Rimm..) is also allowed to be put in ( i got written permission). I don't know anymore if it's in at the moment to be honest.

When i'm not at work, i'm always happy to assist.

**Comment by Bruce-LXXVI** [comment]
Hi all.
Nice to see so much progress in this project. I played around with the code and implemented plotManagement by @DevZupa.
Set DZE_plotManagement=false; to disable it.

**Comment by SmokeyBR** [comment]
any interest of also adding "Build Vectors" to the core code ?

http://epochmod.com/forum/topic/15251-release-build-vectors-rotate-objects-in-dayz-epoch-v234-p4l-non-p4l/

**Comment by AirwavesMan** [comment]
I think thats a good idea.

**Comment by icomrade** [comment]
As do I, I've messaged the author @strikerforce on the epoch forum for permission to include it. If he's okay with it I'll include it.

**Comment by strikerforce** [comment]
@icomrade, go for it!

**Comment by AirwavesMan** [comment]
what about crashed loot and zombie camo? 

http://epochmod.com/forum/topic/29160-release-crashloot-scatter-lootgear-from-destroyed-player-vehicles-on-ground-version-11/
http://epochmod.com/forum/topic/10107-release-walk-amongst-the-dead-hide-from-zombies-like-the-walking-dead/

**Comment by icomrade** [comment]
They seem very cool, but I just don't see a real reason why they would be better off as part of the Epoch base. It takes time to merge and test mods, adding niche mods like these are perhaps not the best use of time.

**Comment by AirwavesMan** [comment]
You are right but I think that after the new epoch version most mods will stop working in particular mods that are integrated in the old epoch code. I took a short review about the new and the old code and think it should work with new epoch version.
Is there any chance that we can add zombie models for the missionfile?

**Comment by icomrade** [comment]
Textures and sound effects should work well enough, but I've never tried adding models to the mission. If you've gotten it to work in the past nothing should prevent it now. As for the above 2 mods some things have changed like variable name which you will need to make sure are update, one I noticed right away was dayz_combat. eBay has been keeping track of changed variables here: https://github.com/EpochModTeam/DayZ-Epoch/blob/765b035764f9b62d3d2bfc18ff9fe62a2c24edc9/Documents/1.0.6%20Variable%20Name%20Changes.txt

Unfortunately, either the community or the script's creators will have to update the code since there's really too many community scripts for us to handle.

**Comment by strikerforce** [comment]
@AirwavesMan crash loot is a very simplistic modification. It shouldn't be all that difficult to add back in for the server owners. Likewise with zombie camo. It would be in the best interest to keep the simple things out of the main epoch code and add the more useful and difficult modifications to prevent inflating the base code with "candy" that could decrease performance.

**Comment by oiad** [comment]
Now that Door Managment is merged, I remember when setting it up on my own server that @ebaydayz recommended changing the maintanence SQL event, I'm thinking this will still need to be done in this version?

`UPDATE `object_data` SET `Damage`=0.2 WHERE `ObjectUID` <> 0 AND `CharacterID` <> 0 AND `Datestamp` < DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY) AND ( (`Inventory` IS NULL) OR (`Inventory` = '[]') OR (`Classname` IN ('Land_DZE_GarageWoodDoorLocked','Land_DZE_LargeWoodDoorLocked','Land_DZE_WoodDoorLocked','CinderWallDoorLocked_DZ','CinderWallDoorSmallLocked_DZ')))` is what I am running at the moment.

**Comment by ebaydayz** [comment]
Done @oiad https://github.com/EpochModTeam/DayZ-Epoch/commit/eae4428e9fc6e1b5eb7347c8702342224ed84d2a

**Comment by oiad** [comment]
So I was doing some testing with doors and door managment. It seems now I can only unlock a door (eyescan or manual code) I don't get the option to lock it and I never get an option to downgrade it.

**Comment by ebaydayz** [comment]
It's most likely an issue in fn_selfActions. I will be reviewing and testing commits from Plot For Life (May 2) to present for the first time over the next two weeks, so I'm sure there are plenty of other building issues atm too.

**Comment by oiad** [comment]
@ebaydayz: I managed to fix the door problem, I can now unlock correctly, relock and downgrade my doors. I traced the issue to: `Configs/RscDisplay/doorManagement/doorAccess.hpp:7:     onUnload = "if(keypadCancel) then {DZE_Lock_Door = ''; [] spawn keyPadReset;} else {DZE_Lock_Door = dayz_playerUID;};";`

When you unlock the door, player_unlockDoor.sqf sets DZE_Lock_Door to the door code, that hpp is setting it to the playerUID so the triggers in fn_selfActions will not work.

My debug lines for the above code:

`"downgrade: dze_lock_door: 76561197999617086 charID: 971 keypadcancel: false"`

I set that doorAccess.hpp file to: `onUnload = "if(keypadCancel) then {DZE_Lock_Door = ''; [] spawn keyPadReset;};";` and it works as expected.

Debug lines for above code:

`"downgrade: dze_lock_door: 971 charID: 971 keypadcancel: false"`

**Comment by icomrade** [comment]
Closing because this issue has been completed and single currency will not be added. However, if someone is able to test single currency with 1.0.6 (specifically the integrated version of advanced trading) they can post bugs to the 1.0.6 issues/testing issue and advanced trading will be fixed accordingly.
