### ISSUE TITLE
[question] key generation algorithm 

### ISSUE THREAD

**Issue by igran** [EpochModTeam/DayZ-Epoch#1692]
how to get from 18a0 to 873 and from 874 to dab0?

**Comment by icomrade** [comment]
you can see how the key is generated here https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/actions/AdvancedTrading/functions/z_at_buyItems.sqf#L106-L141

The vehicle parameters including the key number are send to the database through this file which pulls the keyid/CharacterID for the vehicle (which controls which key to use) from the config files. https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_server/compile/server_publishVehicle2.sqf#L21

The KeyIDs are stored here: https://raw.githubusercontent.com/EpochModTeam/DayZ-Epoch/master/SQF/dayz_code/Configs/CfgWeapons/Item/ItemKeys.hpp

so if you want to add the key with the ID you want to your inventory execute this ```player addWeapon "ItemKeyGreen874";```

otherwise if you want to change the key for the vehicle you would do
```_object setVariable ["CharacterID", "874", true];```

**Comment by igran** [comment]
you misunderstood me, I want to understand how to get from  Green Key (cf27)  to keyid 8? or all hex values are random?

**Comment by icomrade** [comment]
I posted the relevant code and steps to change the key that locks a vehicle, I don't understand how that doesn't answer your question. key values are not random, they are randomly selected. the bit of unique identifier in the key name that you see in game is only for visual reference and cannot be used to generate a key in game, for that you have to use the KeyID.

**Comment by igran** [comment]
no you misunderstood me again, but i have been founded answer

**Comment by icomrade** [comment]
For future reference do not ask general questions on the GitHub issues page, hop on the Epoch Discord or use the Epoch forum. Also, if you are being misunderstood try to ask more concise and complete questions, with the way your original question and response were worded you are lucky I replied at all.
