### ISSUE TITLE
Ghillie for females

### ISSUE THREAD

**Issue by ndavalos** [EpochModTeam/DayZ-Epoch#1750]
I don't know if this is possible, but I have had a few female friends that bemoan the fact that they can't wear ghillies in the past (unless this has changed recently)

Based on this: https://github.com/EpochModTeam/DayZ-Epoch/pull/1749/commits/2ae2d3b9ef93da1d1df9365ab01da5a86c3be030

I was wondering if it would be possible to add a female ghillie or at least add the option for females to wear them.

**Comment by ebaydayz** [comment]
If someone wants to start making models again then sure. But atm we have no modelers. I will quote razor on the second part since this was recently asked in the DayZ discord:

> R4Z0R49 - 08/13/2016
it is possiable but its horible looking. In fact we did have this in a version awhile ago and everyone moaned so it was removed again.
