### ISSUE TITLE
Separate building objects and vehicles in database

### ISSUE THREAD

**Issue by Namindu** [EpochModTeam/DayZ-Epoch#1758]
Im just wondering how hard it would be to separate building objects and vehicles from object_DATA, and make vehicles have there own table (for example 'vehicle_DATA'). I find this way it would be easier to find vehicles and run database events without accidentally delete half a base.

**Comment by icomrade** [comment]
I'm going to close this because I assume I'm the only one that would modify the hive. I just don't see this being useful beyond a slight bit of convenience that can be solved with a pretty straightforward SQL query. you can just filter out the classname table in a SQL query against all of the buildable classes in Epoch, which are probably in the configuration variable files anyway so gathering the list of excluded classnames wouldn't be difficult. In other words the effort does not justify the reward.
