### ISSUE TITLE
Duplicated base doors - fresh 1.0.6 server, lightly modded

### ISSUE THREAD

**Issue by BNG-Lance** [EpochModTeam/DayZ-Epoch#1811]
I've only seen this issue once so far on my 1.0.6 server - duplicated wooden garage doors. Installed were BEC, Infistar 1436, axecop service points, A2Epoch Logistic. Here's the questions I asked the player it happened to - I can get more info if needed..

1. Did you build your base alone or with friends added to plot pole helping you?
    A: A Friend Placed The Plotpole While I Did All The Building.

2. Did you cut down and craft the wood or did you buy supplies?
    A: I Had Harvested And Crafted The Building Materials With A Chainsaw, And Bought The Combination Locks. I Crafted The Garage Doors The Same Day I Placed Them.

3. How many restarts (every 4 hours) do you think it was before your doors duplcated?
    A: Three To Four Restarts At The Most

4. Did the locks duplicate too?
    A: Yes, Locks Duplicated. I Was Able To Remove The Locks And Extra Doors With No Problem, And The Locks Went Into My Inventory Like Normal

5. Has it happened a 2nd time since you removed the duplicate doors?
    A: No I Have Not Noticed This Happen Again.

**Comment by oiad** [comment]
Hi, this is a known problem, seems to happen when doors are upgraded, we are looking into it, cheers

**Comment by icomrade** [comment]
It's been a while since this was reported, I haven't been able to reproduce this myself. So far I've only seen 2 reports by you and another server owner, so this is probably pretty rare. The hiveExt and .RPT (client and server) may be helpful for tracking this down, if it happens again please try and include this info.

**Comment by Clanwarfare** [comment]
Doors are replicating on my 106 server now. It seems to double when players take ownership of an already placed plot.

**Comment by LWBUK** [comment]
Players still experiencing this occasionally even after fix applied.  Earlier today one player had 2-3 doors for every 1 throughout a base. 
He reported it was his base but the plot pole had been removed. He placed a new one and took ownership of all items. After restart the doors had all duplicated. 

I have a the new edited plot_take_ownership.sqf in my mission and the call in fn_selfactions has been amended to suit. 

I can't see anything in the rpt relating to this on a cursory look, but I shall look with more detail shortly.

**Comment by ebayShopper** [comment]
I went ahead and removed the plot take ownership feature. It was poorly implemented, since it needlessly deletes and recreates all the objects on the plot. To do that it sends up to 100 publicVariableServer per second. PVS are not instant. They can take up to a second to finish sending depending on server load and client connection. It only waits 0.01s between each request to delete the object and the subsequent request to publish a new one, so it's not surprising it was causing duplicates. This is needlessly hammering the server with hive calls which is not a good idea anyway.

By default replacing a plot pole grants full access to upgrade, downgrade or remove any object on the plot. Whether the ownerPUIDs and characterIDs of the objects belong to the old owner or new owner is irrelevant, so this really isn't needed.

If you don't want to allow base take overs you can just change the access permissions in fn_selfActions. I'll add an "Allow Base Takeovers" setting to do that, along with the one mentioned in #1886 .
