### ISSUE TITLE
Client Performance Issues

### ISSUE THREAD

**Issue by ndavalos** [EpochModTeam/DayZ-Epoch#1816]
Since it kinda got off topic in the snap points issue, putting this out here so we can try and pinpoint where the FPS issues are coming from.

In late September/early October, the client FPS was decent, regularly getting 60fps or so with 7k building objects and vehicles spawned in. Somewhere along the line, things started decreasing and now I'm seeing 36-MAYBE 50 fps on the client. I have pretty good hardware, so I'm getting better fps than most players on my servers. The average fps for most people has been between 10 and just under 30.  My admin has hopped around to other servers and said it's just as bad or worse on other servers. There have been a few comments in the snap issue thread from other people remarking on fps issues.

Testing this morning I noticed that fps is ok and normal for the first couple minutes until I start moving around, then it drops by 20-30 and stays there. I tried taking some of the stuff out of the scheduler on the client to see if that helped and it didn't really.

Few things I've noticed looking briefly at the scheduler code, the building bubble thing should probably run server side instead of the client shouldn't it? Is it really necessary to send so many medical updates to the server since the players sync quite a bit? I haven't been able to pinpoint where the drop in frame rate starts yet, but it's something after initialization. Any other observations would be helpful so we can try and track down some things that may be causing this.

Also, I removed most of the battleye filters for dialogs and controls since they aren't THAT necessary, that helped quite a bit with clients having memory leaks and massive frame drops. I've dealt with scripts.txt freaking out clients before and spoke with Bastian a few times. He basically said that if scripts get spammed at battleye the filters can cause memory leaks in the client because battleye may end up not being able to keep up.

**Comment by icomrade** [comment]
The building bubble is probably better left on the client side, since that's where loot is spawned any way. It shouldn't be too much extra strain on the client, but moving loot spawns to the server may be too much. I'd be more worried about the impact of larger, more evaluation heavy code, such as self actions and damage actions.

I'd wager that the FPS issues are related to the amount of objects on a server, loot pile unfortunately count as well (I wonder if disabled simulation on them would be beneficial). Although, the script filters were added fairly late in development, so it my coincide with not noticing FPS issues until after release. That being said, on a stock test server, with roughly 2,000 objects I get between 40-50 FPS with the extra vanilla map objects turned on.

The amount of objects on the map is really the limiting factor to server and client FPS. We may be able to improve this by added a vehicle bubble, which would enable simulation on nearby vehicles as needed, instead of enabling simulation on all vehicles in server_monitor.sqf (would probably decrease loading time significantly).

**Comment by looter809** [comment]
With 100 vehicles on the map on my test server and everything else default, I get 30 to 40 frames, and I use to get 50 to 70 depending on where I was in 1.0.5.1.

I have DayZ_POI off (which did help slightly) and a snow script off that was also costing me a few frames and some of my players many frames. But the FPS still isn't what it use to be or even close. Someone told me they heard it was because of the Battleye, is that possible/accurate? And now that I think of it, on my test server I have Battleye off anyways, so I wouldn't expect it to be that.

**Comment by ndavalos** [comment]
If you have battleye off then no, there's something else going on. Taking out some of the filters helped, but it was so marginal it might just be coincidence.

Btw, Taviana just is unplayable due to all the problems with that mod in combination with battleye and epoch. Just too many things wrong with the Taviana mod. I'm ditching that map when I get a chance to setup Takistan. A lot of the models in Tavi spam all kinds of errors. Clients get a memory leak from battleye and crash after about 10 minutes. I've always had problems with that mod anyways. It's not really epoch related, but they do fight with each other too, which is why Tavi absolutely has to be listed first in the mod load order.

**Comment by ndavalos** [comment]
@icomrade maybe I'll see what happens if I completely comment out the code in self actions. That was something that I was thinking about too.

I really don't think it's much server side code related. Granted Server side fps drops down to about 15 with like 10 people on, but I'm not terribly concerned with that at the moment. Client is a pretty hot issue for my players at the moment.

I would also consider not broadcasting the med values at all to the server. Just let it happen during player sync. Most people will disconnect normally, and if they don't the server should catch all that on the disconnect anyways. I increased my broadcast time to 60 seconds instead of 30 to decrease network traffic a little.

Everything I spawn in is server side, all custom map objects have simulation disabled. I also moved traders server side. So basically the only thing the clients are spawning in is zombies and loot.

**Comment by looter809** [comment]
I agree with ndavalos. Server FPS is fine, but client FPS is pretty bad.

**Comment by ebayShopper** [comment]
We did change the zombie behavior pretty significantly near the end of the test builds phase (October 14th):
https://github.com/EpochModTeam/DayZ-Epoch/commit/0da569acad64b670ce777c4a35aa6c62791114f8

Try the new zombie_agent.fsm, R4Z0R said it should improve performance for clients:
https://github.com/EpochModTeam/DayZ-Epoch/commit/5094e61723f9336c6e023588454e8b7fe0effcae

**Comment by ndavalos** [comment]
That's about when things I think started showing different performance, and that probably makes sense with the timing I see with the framerate drop. I'll use that fsm and see how it goes while I'm working on other stuff.

**Comment by ndavalos** [comment]
@ebayShopper no change in client performance with the new zombie fsm.

**Comment by ndavalos** [comment]
I'm pretty sure it's self actions causing the problem. It appears that when I look at terrain it's fine, as soon as I start getting a cursor target it drops wildly. I'll have to go through self actions and see what I can figure out.

**Comment by looter809** [comment]
I feel the FPS drop every where. Not just looking at the terrain. But let me know if you can fix it by turning off some self actions.

**Comment by ndavalos** [comment]
I've been messing with it a little this morning, removing self actions and gear menu checks completely doesn't do anything for performance. I'm 99% sure it's most of the code in the scheduler. For instance there's a for loop in the animal stuff, which is usually 100x slower than any other type of loop. I marginally increased fps by turning that off completely. I'm going to have to fool with all the code in the scheduler on the client to see what's impacting performance the most.

**Comment by icomrade** [comment]
Just out of curiosity, how much FPS do you gain by commenting this code out? I have a feeling that disabling then enabling simulation later (for a large quantity of objects/vehicles) is intensive. https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_server/system/server_monitor.sqf#L324-L328

**Comment by ndavalos** [comment]
Just a few fps, not by much. I'm curious if the buildables have simulation enabled, that might explain why getting near base objects severely drops fps. It seems like whenever I unlock a door and start moving around in a base the fps drops almost by 20.

**Comment by ndavalos** [comment]
Just making a note of some things from the previously closed issue that was a duplicate of this:

On the usage of nearObject/nearestObjects - 

> The lighting objects code seems to call it a lot, most of the other stuff isn't used except for specific situations I think. I'm not sure about the lighting. Also fn_isInsideBuilding.sqf might be looked at as well. You might want to only call that when necessary? Not sure how often it's called.
> 
> Also fn_waitforobject may need to be looked at as well as player_spawnCheck.sqf. The CH53e config also has some code that uses nearestobjects. fn_temperatur.sqf and fn_upgradeActions.sqf might be looked at as well. fn_niceSpot.sqf - not sure how often that's called.
> 
> building_spawnLoot.sqf seems to use it repeatedly.

I think a good place to start looking at the usage would be:
1. All the lighting scripts (not sure how often this is called)
2. All the scripts involved in spawning loot (player_spawnCheck.sqf, building_spawnLoot.sqf) - this may be one of the bigger usages of near and nearest
3. How often fn_isInsideBuilding.sqf is getting called and it's usage of nearestObjects (executes a lot I think)
4. fn_temperatur.sqf (searches for fireplaces/fire things - executes a lot)
5. fn_upgradeActions.sqf (this starts using it if there's no cursortarget I believe)

The code for the CH53 is probably unnecessary since most lift/tow scripts don't care about the strop.

**Comment by ebayShopper** [comment]
[Axe cop's lighting is disabled by default](https://github.com/EpochModTeam/DayZ-Epoch/blob/master/Server%20Files/MPMissions/DayZ_Epoch_11.Chernarus/init.sqf#L145), same as 1.0.5.1. It's a neat feature, but well known FPS killer.

**Comment by ndavalos** [comment]
I just noticed something else hanging out on my napf server. I moved a bunch of dead AI to my position, piled them up, deleted them all and my fps jumped up to 60. I'm thinking I might take a look at disabling simulation on dead bodies.

**Comment by ndavalos** [comment]
I also noticed that the particle effects from flames will cause a frame drop and client crash, that may be gpu driver related though.

**Comment by oiad** [comment]
Did you apply the fix for the zombies in the buildings etc? https://github.com/EpochModTeam/DayZ-Epoch/commit/101a6fc698686c89ab6601d4d1bf331e7a5056b8 I'm quite interested to see if this makes a difference

**Comment by ndavalos** [comment]
No, I haven't, I can't really update with the current repository without making new projects right now. Haven't had the time to go through the trouble and merge things again.

**Comment by oiad** [comment]
@ndavalos any more updates on FPS? I have some fixes in the works for flies (disabling them/moving them from spawning till later) which made a difference

**Comment by ndavalos** [comment]
I've been in the middle of moving, and fixing problems here and there when I get the chance so, no.

I have to figure out why my zombies don't attack ATM.

**Comment by looter809** [comment]
@oiad how much of a difference did you see?

**Comment by icomrade** [comment]
You might have already seen the fix, but if not this might be related to your zombie issues. https://github.com/EpochModTeam/DayZ-Epoch/issues/1819

**Comment by oiad** [comment]
@looter809 hard to say but it has to be better, as it stands now we are applying flies to a body every 2 minutes from death (or until sched gets to it) on my server i've pushed that out to 10 minutes. 

Each body gets a public variable client done on it to each connected player for flies every 2 minues also which can be a lot of traffic.

I really noticed it when I killed about 0 ai and moved them to me with setPos: (```{ _x setPos getPos player} forEach allDead;```

once the scheduler adds the flies the fps takes a dramatic fall

**Comment by icomrade** [comment]
Honestly, I think we can remove flies, I don't feel they warrant any additional benefit other than nostalgia. If they produce a noticeable decrease in performance, then it's not worth it

**Comment by oiad** [comment]
I am okay with removing them but I feel like it should be a config variable to turn it off with the default being off, moving the fly spawning timer out say 10-15 minutes is a good idea as well.

**Comment by minner4068** [comment]
I found a noticeable different in fps when:
* Remove onEachFrame calls and changing the DZGM group icons to refresh every 0.2 seconds (didnt affect gameplay unless you were spinning in circles with 10 people in your group, it would kinda get unusual. There is actually a default group icons part of the game which i plan to switch to. @ GroupIcons 

* Disabling the town generator system, nobody used it after having it enabled for 2 weeks.
* Disabling bloodstains
* Disabling gravity
* Disabling anti teleport

Note, this does open up security issues and what not however i seen a 5-15 fps improvement around the map. Which is quite good, in my opinion.

**Comment by ebayShopper** [comment]
Most of the things mentioned in this issue are done now:

- Group icons are moved to a separate slower loop and the group system is disabled by default.
- The town generator, comfrey plant spawner and plant hint loops are fully disabled when dayz_townGenerator=false; now.
- AntiTP and scheduled security loops are fully disabled when dayz_antihack=0 now.
- The fn_upgradeActions loop is removed. Vanilla buildables now have their actions in their configs. We don't use them anyway.
- The default value for dayz_bleedingeffect is now 2. This disables blood stains on the ground which have a heavy performance impact.
- Flies now spawn ten minutes after death instead of right away. Flies are also disabled by default.
- The 50m nearestObjects search for WaterHoleProxy and Land_Pumpa in fn_selfActions is removed.
- Vanilla antiwall, POI, infectious waterhole and infected camp map additions are now disabled by default. POI are moved back to local instead of global.
- RadioProtocolEmpty may have been causing some crashes. It was breaking some AI behavior so it is removed now.
- The radius in player_spawnCheck for loot and zombies has been lowered to 200m and switched to nearObjects instead of nearestObjects (same as 1051)

As @ndavalos pointed out, the 300m nearestObjects search in player_spawnCheck every 6 seconds was probably the biggest difference. 1051 had this at 200m, nearObjects instead of nearestObjects and every 14 seconds instead of every 6. 1051 also ran fn_selfActions and fn_damageActions every 0.5 seconds instead of every 0.1. These periods can be adjusted in sched_init.sqf, but I'm not going to mess with them. They probably even out based on the time difference between the scheduler tasks (unscheduled) versus spawned SQF threads with sleep (scheduled) anyway.
