### ISSUE TITLE
GetOut event handler

### ISSUE THREAD

**Issue by ndavalos** [EpochModTeam/DayZ-Epoch#1817]
In 105 there was some code to try and prevent getting out of a vehicle and glitching into a base. That seems to be gone completely now. Granted it didn't always work in 105, but it at least helped a little. Any chance of that getting put back in?

**Comment by ebayShopper** [comment]
Yup, it's still there. We just forgot to add the call for it back to the 0.2s `dayz_gui` loop when it got renamed and moved to `sched_gui`. 
https://github.com/EpochModTeam/DayZ-Epoch/blob/Release_1.0.5.1/SQF/dayz_code/system/player_monitor.fsm#L1222-L1242

Since we have a vehicle getOut EH on clients now it is more efficient to just add it to that. Done, thanks.
