### ISSUE TITLE
BodyName check in sched_corpses

### ISSUE THREAD

**Issue by ndavalos** [EpochModTeam/DayZ-Epoch#1818]
While you tried to use a body name to check to see if a body could be deleted, the if statement evals and just goes straight to a delete regardless. It appears you did that to remove "ghost" players. So basically you're deleting AI that have their body names set anyways.

**Comment by oiad** [comment]
My AI don't get cleaned up from this change, WAI/DMZS still clean up as per normal

**Comment by ndavalos** [comment]
Ok, well I'm setting body name and discovered it jumps to 
_x call sched_co_deleteVehicle;
_delQtyG = _delQtyG + 1;

My players are reporting that it's happening on all the other servers they play on, I fixed it on my own, but figured I'd mention it since most people won't know what to do about it.

**Comment by ebayShopper** [comment]
In order for a corpse to be deleted immediately (without normal 40 min wait) it has to meet these conditions:
1. Local to server and inherits from "CAManBase"
2. Is not a zombie
3. Has no "bodyName" variable set on it or has "bodyName" set to an empty string on it.
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_server/system/scheduler/sched_corpses.sqf#L43-L44

Added AI units will meet all those conditions when they die. That is why I added a comment that you need to setVariable bodyName on them. I also submitted pull requests to WAI and DZMS to add that. Setting it to anything besides an empty string "" will work. Also you only need to set it locally on the server, since it is only checked on the server. Unless you want players to be able to see some name other than "unknown" when they click study body on their corpses.

For stuff like this you may want to just shoot a pm on discord:
https://epochmod.com/forum/topic/41542-a2-epoch-discord/
