### ISSUE TITLE
FPS Issue observation

### ISSUE THREAD

**Issue by schwanzkopfhegel** [EpochModTeam/DayZ-Epoch#1832]
Hey,

I have found out that the mass graves cause huge FPS issues on client side.
![20161226213935_1](https://cloud.githubusercontent.com/assets/24301205/21486394/20465b12-cbb4-11e6-9300-48e7f8008c4e.jpg)

If you are near one you have like 20 FPS less than normal.
Can you Guys proof this? Is it worth to remove them from the POIs?

**Comment by ndavalos** [comment]
Interesting, I'm not using poi but maybe tht's somewhere to start looking at stuff. Been so busy lately I haven't had time to examine much.

**Comment by icomrade** [comment]
What FPS do you have with POIs disabled? also the #monitor output

**Comment by oiad** [comment]
I noticed last night when I was testing my fill/drink water changes that the infected water at Pobeda you definitely see a fps drop. (Client 40-50 fps, server 50fps solid)

But when you actually search for all objects nearby, there's a HUGE amount there due to the infected bodies etc so it's no wonder

**Comment by looter809** [comment]
With POIs disabled, I get 30FPS +/- a few anywhere on the client and 50 solid FPS server side. Before 1.0.6 I got 60 to 70 FPS in the same circumstances.

**Comment by oiad** [comment]
It's worth noting that there is a lot of nearobjects being called with searching for all objects in dayz_code:
`[oiad@gateway /storage/pb/repos/DayZ-Epoch/SQF/dayz_code]$ grep -irn nearestObjects * | grep \\[\\]
actions/player_mineStone.sqf:19:} foreach nearestObjects [getPosATL player, [], 8];
actions/player_chopWood.sqf:16:} count nearestObjects [getPosATL player, [], 20];
actions/player_goFishing.sqf:29:} count nearestObjects [player, [], 50];
actions/player_findLights.sqf:24:} count nearestObjects [([player] call FNC_getPos), [], 20];
actions/player_harvestPlant.sqf:42:} count nearestObjects [([player] call FNC_getPos), [], 10];
compile/fn_nearWaterHole.sqf:19:        } count (nearestObjects [_x, [], 1]);
compile/fn_niceSpot.sqf:138:    _objectsPond = nearestObjects [_new, [], 100];
compile/client_plantSpawner.sqf:39:                     and {(0 == count (nearestObjects [_plantpos, [], 3]))} )} ) then {
compile/player_harvest.sqf:16:  } count nearestObjects [getPosATL player, [], 20];
compile/fn_lightFunctions.sqf:26:       } count nearestObjects [([_target] call FNC_getPos), [], _rng];`

**Comment by ndavalos** [comment]
The lighting objects code seems to call it a lot, most of the other stuff isn't used except for specific situations I think. I'm not sure about the lighting. Also fn_isInsideBuilding.sqf  might be looked at as well. You might want to only call that when necessary? Not sure how often it's called.

Also fn_waitforobject may need to be looked at as well as player_spawnCheck.sqf. The CH53e config also has some code that uses nearestobjects. fn_temperatur.sqf and fn_upgradeActions.sqf  might be looked at as well. fn_niceSpot.sqf - not sure how often that's called.

building_spawnLoot.sqf  seems to use it repeatedly.

**Comment by schwanzkopfhegel** [comment]
First of all I want to correct myself: There are no Massgraves in the POIs. But testing proofed that those massgraves mess up the FPS. (This could be important for custom map additions, as many server owners have them added)

Further Testing showed:
Server runtime: 10 minutes, just tested at krastnostav airfield, vanilla server (but infistar was installed)
POI ON: Client Fps: average: 20, max. 25, min. 12
              Server Fps: average: 46
              used RAM: 525MB
POI OFF: Client Fps: average: 28, max. 40, min. 22
               Server Fps: average: 47
               used RAM: 508MB

**Comment by ebayShopper** [comment]
`Mass_grave` is a default A2 object made by Bohemia. It's been used in DayZ mod since the beginning because it fits the atmosphere. But it probably does hurt client FPS when you are close to it, since it is more taxing to render all the flies, particles and what not. If you don't want to use them you can remove or replace them.

It is used in the town generator and infectious water holes. The town generator is disabled by default already, and I just set infectious water holes and POI to disabled by default for 1.0.6.1 3176e16. The POI will also be moved back to local spawned. 

NearestObjects or nearobjects is required in some cases because nearEntities does not work for all object types. Also the empty array searches are required for ambient map objects that do not have class names. Examples are trees, rocks, ponds, wells, etc. which can only be found via fnc_inString on their model name. Waterholeproxy are objects the vanilla devs manually added in the editor. They've only been added on Chernarus, so searching for them will not work to detect certain ponds and wells on other maps. 

The 50m nearestObjects onEachFrame search for waterHoleProxy and Land_pumpa in fn_selfActions was already removed for 1.0.6.1 with 4d3f707. Notice it is commented out now.

Lets move general FPS talk back to #1816 since this issue is drifting off into a duplicate.
