### ISSUE TITLE
Sound delays/queuing in some circumstances

### ISSUE THREAD

**Issue by clontarfx** [EpochModTeam/DayZ-Epoch#1841]
Clients seem to queue sounds after either spamming a drink addAction, eating or drinking cans in quick succession. You can perform a series of actions such as eating lots of cans/drinking/opening gear/firing, and the sounds will be delayed, often being played several seconds after the action was performed.

It seems as if some sounds/actions cannot be performed concurrently, resulting in queuing on the client and server.

**Comment by clontarfx** [comment]
Further testing shows crafting then opening gear/backpack is an easy replication.

**Comment by icomrade** [comment]
I don't think there's much to improve here. The script is fairly lean as is, it may just be that the "Say" command does not allow for more than 1 sound at a time, and queues as described on its own.

https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/compile/object_speak.sqf
https://community.bistudio.com/wiki/say

**Comment by clontarfx** [comment]
Yeah I didn't assume that it was due to script processing delay (server is running 50 FPS with 1 client during reproduction). It likely is some limitation of the say command. Just thought I'd raise it as a minor gameplay affecting bug 👍

**Comment by icomrade** [comment]
I wouldn't use playsound, the minor nuance of hearing a sound later with say is worth the performance benefit over playsound.

**Comment by ebayShopper** [comment]
The way the drink, eat and gear sound effects are played hasn't changed from 1051. You can see that by looking the history of [object_speak.sqf](https://github.com/EpochModTeam/DayZ-Epoch/commits/master/SQF/dayz_code/compile/object_speak.sqf) and [ui_gear_sound](https://github.com/EpochModTeam/DayZ-Epoch/commits/master/SQF/dayz_code/compile/ui_gear_sound.sqf).

1051 player_eat and drink call zombieSpeak the same way as player_consume and drink do now. There was no cool down timer before and there still isn't now. 
https://github.com/EpochModTeam/DayZ-Epoch/blob/Release_1.0.5.1/SQF/dayz_code/actions/player_eat.sqf#L40-L42
https://github.com/EpochModTeam/DayZ-Epoch/blob/Release_1.0.5.1/SQF/dayz_code/actions/player_drink.sqf#L40

The delay is more noticeable when drinking because the script takes serveral seconds to search for nearby ponds and wells before it plays the sound. Same issue as #1835
