### ISSUE TITLE
Bug or nice Feature?

### ISSUE THREAD

**Issue by coresync2k** [EpochModTeam/DayZ-Epoch#1855]
When I near of "KamazRefuel" a car in which I'm sitting starts refueling. If near other refuel-truck it no effect. 

https://www.youtube.com/watch?v=O_Bvo5Az4uc&feature=youtu.be

**Comment by ebayShopper** [comment]
This is a problem with whatever autorefuel script you are using. There is no autorefuel included in 1.0.6.

**Comment by icomrade** [comment]
Actually, that might be a non_DZ version of the refuel truck. What's the class name?

**Comment by ebayShopper** [comment]
Negative, I just tested all the Kamaz refuel including the non-_DZ one. Also search for "Refueling" string in dayz_code and you will see there is no case where it is used in cutText or rolling messages by itself like that.

**Comment by ebayShopper** [comment]
My mistake, I didn't realize this is a feature built into A2 for all fuel trucks. To disable it `transportFuel=0;` must be in the config. @McKeighan accidentally removed it for the KamazRefuel_DZ in 0701e5b. So the `KamazRefuel_DZ` and its child classes `KamazRefuel_DZE1, KamazRefuel_DZE2, KamazRefuel_DZE3 and KamazRefuel_DZE4` will have this problem until the next patch unfortunately.

Sorry I didn't notice this when I tested. You need to get in the driver seat of the truck first for it to work, so that's why I didn't catch it the first time. But the "Refueling" string is indeed from the A2 stringtable.

Fixed with 3f3d8ce.
