### ISSUE TITLE
Unable to remove Lightpole

### ISSUE THREAD

**Issue by TheZog** [EpochModTeam/DayZ-Epoch#1859]
I can maintain/fix damaged lightpoles, but I can't remove one like I can any of the other modular building pieces (walls, floors, ceilings, sheds, firebarrels, etc). It doesn't offer the option to remove it.

**Comment by oiad** [comment]
I get the option to remove my one, are you on the plot pole you're trying to remove it from? 
Are you using DZE_permanentPlot = true?

**Comment by TheZog** [comment]
Yes, I left the default value of 'DZE_permanentPlot = true'. 
I do have the proper tools and can remove the other building items just fine. Are the lightpoles different somehow from the other pieces?

**Comment by ebayShopper** [comment]
Buildables that inherit directly from an Arma class instead of `BuiltItems` or `ModularItems` will have this problem if they aren't added to DZE_isRemovable. [It was the same issue with CanvasHut_DZ](https://github.com/EpochModTeam/DayZ-Epoch/commit/41324139ebf51e10370e1600f1351742854b93cc). Please reopen if you notice any others that are missing.

**Comment by TheZog** [comment]
Thanks as always!
I'll keep an eye out for any other items that can't be removed.

**Comment by ebayShopper** [comment]
From looking at the CfgVehicles configs this should be the last of them.
```
LightPole_DZ, DeerStand_DZ, MetalGate_DZ and StickFence_DZ
```
