### ISSUE TITLE
"panic" voice sound plays too often

### ISSUE THREAD

**Issue by DeVloek** [EpochModTeam/DayZ-Epoch#1861]
When you are very low on blood and zombies are in the vicinity, the player character will make some "panic" sounds. It seems like the more zombies are around the more often this sound is played, often two or three times in a very short time while moving thru a horde, which results in the sounds overlapping with each other.
I suggest adding a timer, so the sound is only played once every few minutes. Adding an option to turn it off completely would be even better. It's more or less a "zombie radar", which makes avoiding zombies too easy in my opinion.

**Comment by ebayShopper** [comment]
It has a 1/6 chance to play every 1 second (player_zombieCheck loop) only when you are less than 50% blood and a zombie takes a swing at you. So it isn't exactly a zombie radar:

https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/compile/player_zombieCheck.sqf#L129-L136

But you are correct, the sound tracks are 4-9 seconds, so they do overlap when played on one second loop. I added a cooldown so that won't happen anymore.
