### ISSUE TITLE
Night Vision

### ISSUE THREAD

**Issue by schwanzkopfhegel** [EpochModTeam/DayZ-Epoch#1876]
If you respawn as a Zed and press the night vision key, you are not able to turn night vision off again.

**Comment by ebayShopper** [comment]
It has a cooldown. It works again after about three seconds. It's always been that way:
https://github.com/EpochModTeam/DayZ-Epoch/blob/33cb816aceaddc96458f42a96e52af5f0b04171a/SQF/dayz_code/actions/pzombie/pz_vision.sqf#L49-L54

I assume it was written like that so the aperture slowly fades in instead of being instant. But I see how it can be confusing. From briefly testing it looks the same either way, so I just removed it.

If someone knows some other reason the cool down needs to be there please leave a comment.
