### ISSUE TITLE
Where's the beef...

### ISSUE THREAD

**Issue by looonytoonz** [EpochModTeam/DayZ-Epoch#1889]
haven't seen a cow in i don't know how long.... i tried raising the maxAnimals count to 15 but still haven't seen any.... is there another spot i should look for issues with this ?

dayz_maxAnimals = 15; // Default: 8

**Comment by looter809** [comment]
I haven't seen any issues with animal spawns

**Comment by looonytoonz** [comment]
maybe it is just my server then... i cant find any related errors in the rpt

**Comment by looonytoonz** [comment]
maybe i will krank the number up to an insane amount and see if anything happens

**Comment by looter809** [comment]
Are you using admin tools to teleport to big open fields?

**Comment by looonytoonz** [comment]
yes, then i sit there for a large amount of time as i know there can sometimes be a little delay of spawned / available items

**Comment by looter809** [comment]
Are other animals spawning but only not cows?

**Comment by looonytoonz** [comment]
i have been running through the woods for about a half hr and seen nothing

people report killing rabbits yesterday

**Comment by looonytoonz** [comment]
just spotted a rabbit.......

**Comment by looter809** [comment]
I just asked my people, they say they have been seeing cows etc. Are you sure you have dayz_maxAnimals = 15; // Default: 8 correct in your init and it's not being called anywhere else?

**Comment by ebayShopper** [comment]
There is no point in speculating. Use a script to mark the animals on the map. You will see 3-6 spawn around your player every time you login within the dayz_animalDistance radius.

Cow and sheep are the rarest animals which explains why you don't get them that often. You can adjust that here:
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/system/scheduler/sched_animals.sqf#L48

**Comment by looonytoonz** [comment]
correct... i am not sure where else it could be called from aside from the:

dayz_code.pbo/init/variables.sqf     which is still set to the default of

dayz_maxAnimals = 5;


but in my mission init i have it set to 15

**Comment by looonytoonz** [comment]
ebayShopper - i installed that tool and the only animal showing up is the rabbit... i have changed the following in hopes of forcing cows and others to spawn more frequently..

changed dayz_code\system\scheduler\sched_animals to:
_animalssupported = ["hen","Cow","Cow","Cow","Sheep","Sheep","Sheep","WildBoar","WildBoar","WildBoar","Goat","Goat","Goat","Rabbit"];

changed mpMission\init.sqf to:  
dayz_maxAnimals = 30; // Default: 8

changed dayz_code\init\variables.sqf to:
//DayZ settings
dayz_lastHumanityChange = diag_tickTime;
dayz_maxAnimals = 30;
dayz_maxPlants = 3;
dayz_animalDistance = 500;
dayz_plantDistance = 500;

**Comment by ebayShopper** [comment]
These are typical distributions I get:

![animals2](https://cloud.githubusercontent.com/assets/7761693/22433865/d9ce839a-e6e7-11e6-9918-fb154e8bea94.jpg)
 
![animals](https://cloud.githubusercontent.com/assets/7761693/22433656/1af134a4-e6e7-11e6-9968-955967abdf69.jpg)

The spawn code is pretty complicated. You could change it to something simpler if you want a guaranteed number, but right now it takes into account client FPS, the number of players online, number of animals already on the map and other factors before it spawns anything.

If you are the only player on the server you will get a fresh random distribution of animals spawned in your area every time you relog, so you can see what you get after a few rolls. It can take up to a few minutes for the nearby animal count to reach the max because the check is called every sixty seconds. It typically maxed out at 5-6 for me. Also they probably won't spawn while you have your map open since your FPS is capped on the map dialog.

**Comment by looonytoonz** [comment]
yeah there are 8 players on currently including myself... i only see the one rabbit close to me...

![animals](https://cloud.githubusercontent.com/assets/24796745/22434113/659fb856-e6e0-11e6-90cf-27eb82a9659c.JPG)

**Comment by looonytoonz** [comment]
i dont know what that means.... do i just remove the red and add the green...? was this an issue for everyone or just me?

**Comment by looonytoonz** [comment]
this is still not working... i had 12 players yesterday and saw the same after updating this file

currently there are 7 players and only 1 animal..... a rabbit

![animals2](https://cloud.githubusercontent.com/assets/24796745/22473907/e9b16f58-e79f-11e6-8ece-4955f3ad331c.JPG)

**Comment by ebayShopper** [comment]
From your screenshot `dayz_maxGlobalAnimals` is undefined. Make sure you didn't remove it from variables.sqf. 

You may want to hop on discord for help, so we aren't spamming people's emails with notifications:
https://epochmod.com/forum/topic/41542-a2-epoch-discord/

**Comment by looonytoonz** [comment]
i am in discord currently....   as for the deletion of the dayz_maxGlobalAnimals ... it is still there and set to 30 in an effort to ramp up the animals till i can see them all settings are set as previously posted with the exception of changing that sched_animals.sqf to the updated one you posted

**Comment by looter809** [comment]
Looney, are you using ESS v3?

Sent from Yahoo Mail on Android 
 
  On Tue, Jan 31, 2017 at 8:49 AM, Looony<notifications@github.com> wrote:   
i am in discord currently.... as for the deletion of the dayz_maxGlobalAnimals ... it is still there and set to 30 in an effort to ramp up the animals till i can see them all settings are set as previously posted with the exception of changing that sched_animals.sqf to the updated one you posted

**Comment by looonytoonz** [comment]
"looter809"

i believe so or whatever version it was about a month ago when it was added to the epoch forums

**Comment by looter809** [comment]
I would check that. I believe it has some variables in there. I told ebay about the errors I saw and he said it was probably caused by safe zone script or something. Maybe you could try removing the animal variable wherever you see it in the ESS. Or maybe you are calling ESS in the wrong area of init.sqf

Sent from Yahoo Mail on Android 
 
  On Tue, Jan 31, 2017 at 9:05 AM, Looony<notifications@github.com> wrote:   
"looter809"

i believe so or whatever version it was about a month ago when it was added to the epoch forums

**Comment by looonytoonz** [comment]
it must be something on my end for sure..... i have rented another server for testing, and this one doesnt have the issue. all animals are spawning correctly. i will continue to build it up til i see the animals having issues. then go from there. 

![animalsok](https://cloud.githubusercontent.com/assets/24796745/22491523/bec748a4-e7e9-11e6-8ecb-8197a439694b.JPG)


either way is this change that you submitted earlier still need to be done for everyone ?

"Use playersNumber for player count in sched_animals #1889"
