### ISSUE TITLE
ServerName does not displayed correctly

### ISSUE THREAD

**Issue by dreamforceinc** [EpochModTeam/DayZ-Epoch#1896]
dayZ_serverName = "TESTSERVER";
[https://yadi.sk/i/wZYtGmGd3EAbRK](url)

**Comment by Basti890** [comment]
The Watermark seems only to support up to 6 characters.
I had this Issue on my Epoch 1.0.5.X Server to. I don't know how this is now integrated in the latest Epoch but if it uses the Server-Name from Config, its the worst choice to do so.
Generally there should be a variable which can contain the Watermark and only if its empty, the regular Server-Name is used or no watermark is displayed.

**Comment by oiad** [comment]
It's really not designed to say a full server name, from where i've seen it used it displays a servername like: US434 or similar not "bobs bandit hideout"

**Comment by icomrade** [comment]
The only thing more annoying than a watermark is a long watermark. Despite the name, this variable was never intended to display the whole name, either the clan tag that hosts the server, or a code which is unique to the server. You can create a watermark in a custom debug monitor, which is ideal since it won't take any more screen real estate up, or a semi-transparent server icon.

**Comment by dreamforceinc** [comment]
But it worked in 1051 with "external" script and long servername. I was looking for the differences between 1051 and 106, and did not find them...

**Comment by ebayShopper** [comment]
You can change it by copy pasting the contents of `dayz_code/gui/desciption.hpp` over the include line for that file in description.ext.

 You can make it fit longer text by:
* [increasing the width](https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/gui/description.hpp#L135)
* [decreasing the font size](https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/gui/description.hpp#L148) 

I am not going to change it because I think icomrade is correct. I do not want to alter the original designer's choice to limit it to 15% of the screen at the intended font size. Admins can easily change it if they choose.
