### ISSUE TITLE
spawning swimming in ground

### ISSUE THREAD

**Issue by Cherdenko** [EpochModTeam/DayZ-Epoch#1913]
So it seems like on Napf the Spawn swimming bug does still exist.
im running overpoch 1061 on my server. this bug does not happen to me only but to the whole population of the server
it does not really interrupt the players but its kinda odd if you log in and get shot coz of you swimming in the ground. also sometimes you have to get killed for the bug to disappear.
this does only seem to happen when players login after server restart or after they died

**Comment by ebayShopper** [comment]
You are correct. I tested on a stock Napf server and the issue was still present on relog.

This commit fixes it for me ad7a127. To apply it as a hotfix just add the code at the bottom of server_functions.sqf. The other two files do not need to be changed.

 I only tested by myself, so please test on a server with multiple players relogging at the same time. Leave a comment if you still have the problem after that and I will reopen this. Thanks.

**Comment by ndavalos** [comment]
I've done numerous fixes for non-chernarus maps for this, while I've gotten most instances fixed, it still happens if someone does not log out normally (easiest way to reproduce it, still happens randomly if logging out normally too). I am going to try and popping them into the ground instead of above it since, if you notice, the player stops swimming once the model ends up chest high into the terrain. Checking the animation then adjusting to chest high may fix it, or at least give the player the ability to pop out by moving.

**Comment by Cherdenko** [comment]
So either im just stupid or this doesnt work.

**Comment by ebayShopper** [comment]
Did you apply the change to player_monitor.fsm and player_switchModel.sqf?
https://github.com/EpochModTeam/DayZ-Epoch/commit/6a711deccc51ed8e98a92257c1238683223cf6e9

You have to overwrite the path in mission\init.sqf to player_monitor.fsm and the path to player_switchModel.sqf in compiles.sqf. I tested on multiple slopes and different parts of the map. If you are sure you overwrote those two files together please post the coordinates where you can reproduce it on Napf.

**Comment by Cherdenko** [comment]
yes ebay i know how to do that...
tripple checked my filse..
error is still persistent

**Comment by ebayShopper** [comment]
Ok, I see now in your mission you have ESS which does its own setPos. I did not add 6a711de to it yet. [[Added here](https://github.com/ebayShopper/ESSV3/commit/76f7d0bb523d62cbf51df98a327d0e372128cc68)].
