### ISSUE TITLE
Insane FPS drop when executing client side scripts around building additions

### ISSUE THREAD

**Issue by BigEgg17** [EpochModTeam/DayZ-Epoch#1919]
Hello,

I do not know if I am the only one having this issue so please bare with me, but when I do something as simple as deploy a bike or try to place a building object, my fps drops from 60+ to 47ish when I am around building additions (not sure if towns affect this as I get lower fps in them). I have tried several ways of seeing if this was merely the way I was calling the building additions (yes I am using the fnc_spawnObjects) but to no avail. I literally log in, run around Balota, get 60+ fps, but when I do something just slightly on my client, it drops every time. Now, this doesn't happen when doing things such as Opening the Group menu, but it does happen with nearly everything else. 

Again, not sure if it is me, or if it is the update, which is why I am making this post. I get 60+ fps when away from buildings, but boy does it drop it when I am near them.

**Comment by oiad** [comment]
Hello,
We've talked about this quite a lot, every 6 seconds we check for loot to be spawned using nearestObjects which is quite intensive: https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/system/scheduler/sched_init.sqf#L39

**Comment by BigEgg17** [comment]
Oh, that is good to know. Apologies for wasting your time for something I should have a looked a little harder for. Should I just increase it and see if there are bad results?? Because at this point I am willing to sacrifice the 100kb of mission space to make the fps better.... It will also allow me to change the bank variable in the player_fsm which would make me happy haha - I think ill try raising it and let you know if anything bad comes of it.

**Comment by ebayShopper** [comment]
I tested 14s versus 6s and there was no discernible difference. The result of nearObjects is cached, so a frequency change like that should not make much difference.

Yes, being in a town with densely packed buildings like Elektro lowers client FPS. This has always been the case with DayZ mods due to the way the check for loot and zombies works. Having a nearby cursorTarget that is not null also lowers client FPS because it activates [this block](https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/compile/fn_selfActions.sqf#L222) which runs a large number of additional checks every time fn_selfActions is called (0.1 seconds).

As for third party scripts, there are any number of reasons they can cause FPS drops. The forums is better suited to discussion of that.

Optimization is a constant work in progress. We can go back and forth talking about client FPS forever, but it is not productive without objective reproducible results in a controlled environment. "When doing x on a stock test server my game consistently freezes or FPS drops by x. Here are steps to reproduce it and what my RPT logs show.." is a helpful report. Something like "I am running untold number of third party scripts on a live server and my FPS sometimes goes down when I'm doing x" is not helpful.
