### ISSUE TITLE
dayz_rollingMessages FPS issue

### ISSUE THREAD

**Issue by BigEgg17** [EpochModTeam/DayZ-Epoch#1926]
Hello,

I was talking to another server owner (Maximus from Mercs Gaming) about the FPS issue I was having, and he pointed me in the direction of dayz_rollingMessages causing the issue he was having, not the loot tables. This theory sounded more probable, as when I load into areas, the loot is spawned, and I get fantastic FPS, so I tried it.

I turned Vsync off and looked at a hill, and getting 100 fps, I deployed a bike (I disabled the deploy message that used dayz_rollingMessages) and I got no FPS drop, but when I packed the bike (with the packed message not disabled) I received an fps drop down to around 65 fps. 

I re-logged and was again getting 100 fps, I deployed the bike, and just to make sure, I got on the bike (when you get on a deployed vehicle - I have an event handler that will say it deletes on restart, using dayz_rollingMessages) and when the message came up, I received the same 40 fps drop.

I hope this can get fixed :)

**Comment by icomrade** [comment]
I hate to be blunt but anecdotal evidence doesn't do much for an arbitrary issue like FPS. There's any number of things which drop FPS, DayZ_RollingMessages is probably not the cause, rather vehicle creation is. We've discussed this previously in the Discord chat, any time you create a vehicle a host of properties, position, animation state, sounds, physics, etc. are all networked, processed, and constantly updated. The simulation of vehicles is probably, second maybe to simulation of numerous AI, the most significant impact to client FPS, and we've known this for quite a while  (which is why we already disableSimulation for static objects like vehicles). 

I can only speculate at the reason client FPS resets after relog, but, I'd say since the vehicle is local to your client it has the task of keeping track and networking everything about that vehicle to everyone; this may not have much difference in terms of FPS between high pop and low pop. After the owner of the vehicle logs out the server becomes owner, until another client gets into the vehicle.

**Comment by oiad** [comment]
Just a point, too, everything in epoch is now dayz_rollingMessages based so the player would be seeing this constantly, when building, unlocking doors, trading etc. So if it's only doing it while deploying or similar, as @icomrade mentioned that's probably your problem

**Comment by BigEgg17** [comment]
@icomrade - it isn't the bike..... When you do anything with dayz_rollingMessages this happens. Did you read what I wrote?? When there is no dayz_rollingMessage when the bike is deployed, the fps is fine, but when there is a message, the fps drops. This is not a coincidence, and I am not dumb. @oiad, I am seeing this constantly. 

Here is with the "You've deployed a bike" message:
http://imgur.com/a/Al60B

Here is without the deploy message:
http://imgur.com/a/D4RJS

Here is me simply combining mags in my inventory:
http://imgur.com/a/Mt1tU

Here is me simply executing a rolling message using the Test Kit by @ebayShopper:
http://imgur.com/a/lu7pc

Please do not tell me it is the vehicle, it is clearly the messages. If there is no messages, the fps is great. It has nothing to do with the loot at all, it is the messages. Don't know how you could possibly deny the above screenshots....

**Comment by icomrade** [comment]
I don't think me or Oiad meant to offend or upset you, so there's really no need to get defensive.

I fail to see how a message causes FPS drop, it updates similarly to any display - which includes weapon scopes, binoculars, icons on your screen, and  debug monitor. Even if this was the issue there is nothing I would change with the code. I skimmed over your message, specifically parts in parenthesis since they should not contain information of value, which resulted in misreading of the middle paragraph.
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/init/compiles.sqf#L538-L569

Further more, running the following code provides no noticeable FPS drop, and eliminates other variables that may invalidate results, such as creating a vehicle or setvar/pubvar/other networked commands.
````while {true} do {  localize "str_pulse_weak" call dayz_rollingMessages;  uiSleep 0.1;};````

**Comment by ndavalos** [comment]
I honestly think it's self actions. You can get the same fps drop by simply looking at building parts then when you look away the fps goes back up.

**Comment by BigEgg17** [comment]
When I execute that code, I dropped 30 fps @icomrade:
http://imgur.com/a/CJaAr

What else could possibly be the issue???? With using that code with cutText, I get no FPS drop at all. The only thing all of this has in common is the messages. I am just as clueless as to why, but it is them.

**Comment by icomrade** [comment]
No I do not use Vsync. The issue may be the debug monitor FPS not being accurate, rather than an actual FPS drop

**Comment by BigEgg17** [comment]
Not that @icomrade 

http://imgur.com/a/h1JJp

**Comment by icomrade** [comment]
I don't experience that at all.  It also doesn't make sense to me that displaying text would cause sustained FPS drop indefinitely afterwards.

I also, don't ever get above 75 FPS ever, so that may be part of my inability to replicate any drop. with that being said, if this is the case it would be a better indicator that FPS above a certain point cannot be considered stable and should not be used to gauge performance. As an aside, I don't think ~70 FPS is bad, it's actually quite good for ArmA, especially considering commands per second is probably more correlated with playability than FPS.

**Comment by BigEgg17** [comment]
I know it isnt bad, in an open area. When I am in Balota for example, I drop to 45.... Ridiculously low... There has got to be something that is going on. I dunno why it would either, but it is, and it needs to be fixed.

**Comment by ndavalos** [comment]
I've managed to keep fps between 50-60 by increasing the timing on self actions, gravity and one of the other scheduler dealies (I forget which). Also by replacing nearobjects and nearestobjects with nearentities as much as possible (some things you can't).

**Comment by ndavalos** [comment]
Spawn check was the other scheduler thing I increased the timing on, I'm considering breaking zombies and loot into separate scheduler things instead of combining them both into spawn check

**Comment by BigEgg17** [comment]
Again though, the fps issue is all originating with the messages. Everything else is fine on fps, the only issue is the messages and I don't know what to do about them. I'm not just going to leave them, because they make playing in cities and building additions much harder and more annoying.

**Comment by ndavalos** [comment]
Yup, he's right, I just tested it and it permanently lowers your fps by 10 after the first time you call it. Just executing a simple "bleh" call dayz_rollingmessages will lower the frame rate until you log.

**Comment by icomrade** [comment]
Well, I did have Vsync on... which is weird since I was getting FPS which were not multiples or anywhere near a multiple of 15 (and I never enable Vsync in any game). I see a ~10 frame drop now as well, but it still doesn't make sense since literally every UI element and overlay is CutRSC

**Comment by BigEgg17** [comment]
I am just as curious, but it is much more than a 10 fps drop for me, but that could be because I am starting out higher in fps, or other reasons. It makes it worse near building addons. Thank you for re-opening - curious to know what the issue ends up being!

**Comment by ndavalos** [comment]
The stuff I mentioned earlier kick in about 20 seconds after you're logged in and playing since the scheduler starts up delayed, most likely a combination of the two.

**Comment by BigEgg17** [comment]
The scheduler really has no bad fps effect on me, even in the screenshots I posted, I was 30 minutes in and the drop was still around 30 ish - either way I am glad this is re-opened, as it is quite annoying having 40 fps at Balota

**Comment by icomrade** [comment]
Hmm, the layer number of the CutRSC seems to have significant impact on FPS. I can only assume that BIS coded it so if you want to use the top most layer, which we are doing to prevent overlaying, it creates all lower layers prior.

Change ```4099999 cutRsc ["RSC_DZ_Messages","plain"];``` to ```15 cutRsc ["RSC_DZ_Messages","plain"];```

**Comment by ndavalos** [comment]
@BigEgg17 in the interrim if you put this at the bottom of init.sqf:

```
if (hasInterface) {
dayz_rollingMessages = {
	private "_showText";
	disableSerialization;
	_showText = {
		private "_textLine";
		15 cutRsc ["RSC_DZ_Messages","plain"];
		_textLine = (uiNamespace getVariable "DZ_Messages") displayCtrl 4099998;
		_textLine ctrlSetStructuredText (parseText _this);
		_textLine ctrlCommit 0;
	};
	if (typeName _this == "ARRAY") exitWith {(_this select 0) call _showText}; //Special or multi-line message
	if ((diag_ticktime - Message_1_time) < 5) then {
		if ((time - Message_2_time) < 5) then {
			Message_3 = Message_2;
			Message_3_time = Message_2_time;
		} else {
			Message_3 = "";
		};
		
		Message_2 = Message_1;
		Message_2_time = Message_1_time;
	} else {
		Message_2 = "";
		Message_3 = "";
	};

	Message_1 = _this;
	Message_1_time = diag_ticktime;
	(format ["%1<br></br>%2<br></br>%3", Message_1, Message_2, Message_3]) call _showText;
};
};
```
It should fix the problem until the update is released
It's basically just a copy of what icomrade just committed. It loads after compiles so it overwrites the one that gets initialized in compiles.
