### ISSUE TITLE
Very easy duping method

### ISSUE THREAD

**Issue by AirwavesMan** [EpochModTeam/DayZ-Epoch#1938]
Steps:

- standing in front of any storage item, shed, vehicle 
- Put your internet cable off
- pack your backpack in the stoarge item
- press ESC and disconnect to the lobby
- put in your internet cable (should be a message 10 - 15s no connection)
- load in the mission again
- the backpack is in the vehicle or stoarge item and on your back again

This dupe is so common on many servers and it happen many times on my server.

**Comment by ebayShopper** [comment]
Yes, we are aware of this. It existed in 1051 and all previous versions of dayz mod too.

Force save is done when the gear menu is closed, so your inventory doesn't always update in the database if you don't close your gear before force disconnecting.

We probably need to call a force save anytime gear is moved out of your inventory to the ground or a storage object (via left arrow click, double click on slot, surrender, etc.). This is going to significantly increase the number of PVS sent, so if someone knows of a better way then please leave a comment.

**Comment by icomrade** [comment]
Player_Sync gets the weapons cargo straight off of the character object, it should update regardless. https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_server/compile/server_playerSync.sqf#L108-L110

We could just disable opening backpacks on other characters who are in the escape menu, however. Of course, this would require another setvar probably https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/compile/fn_gearMenuChecks.sqf#L11-L39

**Comment by oiad** [comment]
@icomrade in the grand scheme of things another setvar is probably the easiest way, though

**Comment by ebayShopper** [comment]
No, server_playerSync is never called, because the gear menu is never closed. Server_onPlayerDisconnect is unreliable at calling it [for the reason explained in the comment at the top](https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_server/compile/server_onPlayerDisconnect.sqf#L1-L7).

This is not only a problem with backpacks. It is moving anything out of your gear (either to the ground or storage) and then force disconnecting before closing the gear dialog or opening the abort menu (both of which would trigger a force save).

**Comment by SmokeyBR** [comment]
this is getting pretty common...
while trying to find a way to stop it, i have found this 
https://github.com/GhostzGamerz/Dayz/blob/Master/dayz_server/init/server_preventDupe.sqf
https://github.com/GhostzGamerz/Dayz/blob/Master/GG/GG_init.sqf

based on
https://github.com/0verHeaT/DCDupeFix

i tested by myself and it seems to work, might give some ideias, i dont have a full undestanding of how it works. be nice if guys could come up with the blocking opening gear if player in esc menu if thats the way u wanna go on this issue https://github.com/EpochModTeam/DayZ-Epoch/issues/1936

i dont get it why more people are not participating on this as i see people abusing this daily.

**Comment by ndavalos** [comment]
Yeah I'm doing something very similar, except I basically delete all storage objects and vehicles near the player if they disconnect within 10m of them, also delete all backpacks laying on the ground. Then I recreate the objects and put all the stuff back in them. I extended my disconnect with the abort button from 8 to 10m. I don't even care if they have the gear menu open or not since people will use the disconnect method with VON if you are kicking for that as well. I'm a little more harsh with my VON and kill the player and delete the body if they abuse it.

**Comment by SmokeyBR** [comment]
any reason you not using the default VON block from epoch ?
seems to be doing the job after aplying it but now people are abusing the other dupe method https://github.com/EpochModTeam/DayZ-Epoch/issues/1936, if anyone care to share something being looking all over for something close to it so i can adapt it

**Comment by ndavalos** [comment]
Because I want to make sure they die for using VON and lose their stuff. I light them on fire and let them watch themselves burn for using VON on side :) I also send a publicvariabeserver that doesn't have a filter to make sure they're kicked after dying, that way they're also ghosted for a minute.

I may force a gear reload from database for anyone within 10m of someone disconnecting as well, but I'm not going to worry about it too much for now. Have to think that one over a bit more.

**Comment by icomrade** [comment]
If we just kick players from the lobby on D/C then that would probably solve this. there's no real reason to allow someone to sit in the lobby now that I think about it; kicking to the server selection screen on DC would probably discourage combat logging as well.

**Comment by SmokeyBR** [comment]
while i was testing this issue i did notice if i was not quick enough with disconnecting and connecting or if i left the lobby the dupe would not work but i am unsure if that would be enough.

**Comment by Stijnkluiters** [comment]
https://epochmod.com/forum/topic/43887-anti-dupe-1061-exists/#comment-292585

**Comment by icomrade** [comment]
oops wrong one
