### ISSUE TITLE
Can Skip Medic Animation

### ISSUE THREAD

**Issue by SmokeyBR** [EpochModTeam/DayZ-Epoch#1942]
players can easily skip medic animations by jumping (pressing V)
saw players doing it while opening safe.

**Comment by ebayShopper** [comment]
That's because some scripts are missing the interrupt loop. Lock and unlock vault are examples of that.

I do not think locking and unlocking safes should play the medic animation. It is slow, tedious and ill fitting. All you are really doing is opening or closing the door. If there are no objections I will go ahead and take it out of those two.

**Comment by SmokeyBR** [comment]
i thought there was an animation so it give enough time so items can be published, thats what made me worried. if theres no reason to worry i can go either way

**Comment by icomrade** [comment]
Animations are mostly for aesthetics, I suppose populating item inventory may take a small fraction of a second, but it's not usually a problem. I don't think skipping the animation is a problem, and I would not object to removal, since I also see it as a waste of time
