### ISSUE TITLE
Request: Lock doors without knowing the code

### ISSUE THREAD

**Issue by ndavalos** [EpochModTeam/DayZ-Epoch#1944]
Since the lock/unlock conditions were moved to the door definitions for the actions, I was hoping you would consider removing the necessity for having to unlock a door before locking it if the global bar doesn't have the code for the door you are trying to lock. Basically asking for locking a door have no other conditional to it except the door is closed and lockable. Unlocking should remain the same.

Or alternatively allow for customizing the conditional code by sticking it in a function.

**Comment by ebayShopper** [comment]
I don't see a need for those extra conditions on locking doors. It should not be a problem to allow anyone to lock a door without knowing the combination. You can unlock from both sides, so you can't be locked in if you know the code. It is also more convenient for players who do know the code, because they don't need to enter it twice if they interact with another door before locking the previous one.

If I'm missing anything then someone please leave a comment and let me know. I just removed them for now.

**Comment by ndavalos** [comment]
Thanks, I really appreciate it :)
