### ISSUE TITLE
Bug with Round Fence

### ISSUE THREAD

**Issue by dreamforceinc** [EpochModTeam/DayZ-Epoch#1945]
When building a round fence player is sliding. Video:
https://www.youtube.com/watch?v=jXhClo04bT0

**Comment by Basti890** [comment]
This bug comes from vector building (now part of dayz_epoch) as the original 1.0.5.x setting only allowed 180 degrees turning of some object. 
I don't know where the settings are, but  you should be able  to exclude some buildings from vector build. 

The safe must also be exludet as it starts to move you too.

**Comment by oiad** [comment]
It's not vector building, it's because the model doesn't have a ghost  version. The nice wooden shed did the exact same thing. I think this item just needs its distance from the player pushed out before building
