### ISSUE TITLE
Include file z\addons\dayz_code\Configs\RscDisplay\ZSCdefines.hpp not found

### ISSUE THREAD

**Issue by cajlaj** [EpochModTeam/DayZ-Epoch#1953]
i get this error message whilst joining a dayz overpoch server. Help please

**Comment by DAmNRelentless** [comment]
This is not an issue with DayZ-Epoch. Next time I suggest you make a forum post or something like this. The issue section on github is more for bug reporting or suggestions to add more features.

Never the less I think you're getting this problem on clientside, means it's written on your screen. I bet you don't have the newest files of DayZ_Epoch. Because the ZSCdefines.hpp is included in this mod.

**Comment by ndavalos** [comment]
It's usually mod launch order, epoch must be the last mod listed in the launch parameters.

**Comment by icomrade** [comment]
https://epochmod.com/forum/topic/43715-any-talk-about-overpoch-using-epoch-1061/#comment-290826
