### ISSUE TITLE
[1.64] Freeze in AdvancedTrading

### ISSUE THREAD

**Issue by S-fly** [EpochModTeam/DayZ-Epoch#2010]
1.64.144120:  There's a serious game freeze when selecting an attachment, can you confirm this?

**Comment by ebayShopper** [comment]
With the `1.64.144120` test build Dwarden posted I get these errors and I assume you have the same:
```
Version 1.64.144120
Cannot register unknown string STR_MP_KICKED_SLOW_NETWORK
Item STR_DN_LADA_CP listed twice
Item STR_DN_LADA_RED_CP listed twice
Item STR_DN_LADA_WHITE_CP listed twice
Item STR_DN_LADALM_CP listed twice
Item STR_DN_MTVR_REFUEL_CP listed twice
Item STR_DN_USBASICWEAPONSBOX_CP listed twice
Item STR_DN_USLAUNCHERSBOX_CP listed twice
Item STR_DN_USORDNANCEBOX_CP listed twice
Conflicting addon CorePatch_CCP_67542 in 'corepatch_a2\corepatch_ccp_67542\', previous definition in 'CorePatch\corepatch_ccp_67542\'```

The conflicting addon error is most likely causing a loop any time CfgWeapons or CfgMagazines is iterated through which explains the freeze I also saw on all scripts that do that. It is probably because we do not have all the A2 corepatch addon updates yet that will come when it is finally released or pushed to the steam beta branch. Right now we only have the binaries and A2OA corepatch.pbo, so we will have to wait until we get the updated A2 one too.

**Comment by S-fly** [comment]
STR_MP_KICKED_SLOW_NETWORK is the only (new) error in my RPT. I think you didn't used the A2 beta branch. Everything runs smooth with 1.64 - except the attachments. I'll take a closer look tomorrow. 

and hey: thx for your work ;)

**Comment by ebayShopper** [comment]
You are correct. I forgot to update to the beta branches. After using the beta on both A2 and OA I do not have any RPT errors except the one you mentioned.

It looks like 1.64 has considerably slowed down `select` when a config parameter is used.


This is the code I tested with in the editor:
```sqf
_config = configFile >> "CfgWeapons";
_count = count _config;
diag_log format["CfgWeapons count: %1",_count];

for "_i" from 0 to _count-1 do {
	_weapon = _config select _i;
};
```
1.64 has only added 29 new weapon classes (393 --> 422). However, that same code takes 32% longer to run in `1.64.144160` versus `1.63.131129`. This is with no mods loaded except CO:
`-mod=C:\Program Files (x86)\Steam\steamapps\common\Arma 2;Expansion`

When Epoch is added the difference is more pronounced because CfgWeapons totals (13,236 --> 13,265) with all of the ItemKey classes. However, in `1.63.131129` the above code still completes in less than 1 second. In `1.64.144160` it takes over 17 seconds, thus freezing the game for that time if executed unscheduled.

I am not sure if this is a bug we should report to Dwarden or just a side effect of some changes we will have to live with. It is not that noticeable unless dealing with very large configs. What do you think @icomrade ?

**Comment by oiad** [comment]
Seems like something that should definitely be reported

**Comment by ebayShopper** [comment]
Limiting it to 7,000 iterations with CfgWeapons still takes 3.67188 seconds. CfgVehicles is 7,305 entries and it completes in 0.0390625 seconds.

This seems to only be a problem with CfgWeapons when Epoch is loaded, so my guess is something in the weapon configs is conflicting.

**Comment by icomrade** [comment]
I wonder if we could replace the key system with something like a key chain as a physical item and setvar the Key IDs to the player, the hardest part would be handling key chains on the ground or in storage, but I could just add another column to the DB. The whole key system is a mess in regards to the actual implementation, and if this is the way config lookups will be from now on I don't really see a good reason to keep the keys as items if we can get a "key chain" system working

**Comment by ghos7bear** [comment]
Did some tests on non-modded setup (with Corepatch),

`_c = configFile >> "CfgWeapons"; for "_i" from 0 to count _c - 1 do {_c select _i};`
1.63: 0.562701ms
1.64: 1.2416ms

`_c = configFile >> "CfgVehicles"; for "_i" from 0 to count _c - 1 do {_c select _i};`
1.63: 4.7365ms
1.64: 7.7656ms

**Comment by ebayShopper** [comment]
I did some more testing and found the problem. Having `CfgWeapons` for the keys in `dayz_epoch_b.pbo` was responsible. After reverting commit c4682e5 the freeze is gone. Here are the results of running @ghos7bear's code in the editor:
```
1.63.131129 stock:
Code took 0.000999451 seconds to run (weapons)
Code took 0.00801086 seconds to run (vehicles)
With Epoch:
Code took 0.0319977 seconds to run (weapons)
Code took 0.0160065 seconds to run (vehicles)


1.64.144198 stock:
Code took 0.00300598 seconds to run (weapons)
Code took 0.0140076 seconds to run (vehicles)
With Epoch:
Code took 13.213 seconds to run (weapons)
Code took 0.0279999 seconds to run (vehicles)
With DayZ Mod:
Code took 0.00300598 seconds to run (weapons)
Code took 0.0240021 seconds to run (vehicles)
With Epoch and fixed epoch_b
Code took 0.0340042 seconds to run (weapons)
Code took 0.0279999 seconds to run (vehicles)
```
The full RPT can be viewed here: https://pastebin.com/0A5wu7Ts

So the difference is there, but it is negligible. The problem was splitting `CfgWeapons` between `dayz_code.pbo` and `dayz_epoch_b.pbo` for some reason.
