### ISSUE TITLE
New assets

### ISSUE THREAD

**Issue by Helion4** [EpochModTeam/DayZ-Epoch#2020]
@icomrade @ebayShopper  If I were to supply more assets, would it best to use a new folder for it all? And do you have a time-frame for the next update or not?

Cheers. H4

**Comment by ebayShopper** [comment]
We were waiting for the A2OA 1.64 patch. The last commit by icomrade changed vehicle repairs to use new 1.64 only getHit commands.

However, 1.64 is [now available on Steam](https://forums.bohemia.net/forums/topic/213193-arma-2-oa-update-164-build-144629-release-candidate-for-eol-end-of-life/?page=5&tab=comments#comment-3305062) when you opt into the beta branch, so we can test the changes. It is not clear when BI will move it to stable, but they have been making progress.

You could put new assets in `dayz_epoch_b`, since we already have that folder on the git. It is currently not used for anything except one tent texture. If you prefer to not have them on this repo you can make your own. Then we can load it as a separate addon like we did with WillRobinson's Redryder and Anzio. In that case the binarized version would just be packed with 1.0.6.3 at release.
