### ISSUE TITLE
PVCDZ_obj_HideBody

### ISSUE THREAD

**Issue by AirwavesMan** [EpochModTeam/DayZ-Epoch#2030]
Am I correct, that PVCDZ_obj_HideBody is not used at the moment in the game? Hiding a body is working always even without this function. Does the game overrides PVCDZ_obj_HideBody or is not possible to override Arma 2 Hide Body at all?

**Comment by icomrade** [comment]
It's used for gutting animals. It seems to be sent to nearby players, likely to prevent the chance of the animal being visible due to a locality issue or delay and it being gutted twice

https://github.com/EpochModTeam/DayZ-Epoch/blob/392f8cb7b3fe2b466fa9cf920d2879dc8d4aebe0/SQF/dayz_code/compile/local_gutObject.sqf#L32-L45

**Comment by AirwavesMan** [comment]
Question was answered.
