### ISSUE TITLE
Admin Panel?

### ISSUE THREAD

**Issue by prosims** [EpochModTeam/DayZ-Epoch#312]
Are you going to create an admin panel for epoch (something like dayz control center) . I mean the main features would be great like watching the players, watching spawned vehicles on the map, etc. It would help to prevent a lot of cheating. I know Days Control Center will not be released anymore.

I modified your mission files a lot, made bases with bots, patrols, gold rewards, changed spawns and trader items. We are testing now, we are going to make our server open for everyone soon.
I hope you do not mind it. It is now real survival hardcore on the server. Thank you for the mod!

**Comment by Nathan911765** [comment]
So 3 years on I have always like DAYZCC and I used it for vanilla along time ago, I have downloaded the files from @nerdalertdk and have been doing some of my own work to them. I have managed to get stop start and restart to work as I run a dedicated server  and I am working on learning some more PHP so that I can get it all to work with Epoch :) if anyone else has done anything to the files please do share as it would be great if we could get them fully working with Epoch.
