### ISSUE TITLE
Full localization support/Localization topic

### ISSUE THREAD

**Issue by labpaw** [EpochModTeam/DayZ-Epoch#852]
It just a reminder for you guys. Hope to see it in 1.0.4 and higher versions(not in 1.0.3) Don't close this.
Also this issue can be a "localization topic" so if you add new stuff, you can request a translation here.
And for guys who can't(don't know how to) make a PR, post your translations here.
What needs to be done:
- [ ] CfgMagazines.hpp file. All stuff from this should be translatable(or most of them) Prio:Highest
- [ ] cfgVehicles.hpp. Prio:High
- [ ] Heli Towing. player_heliLift.sqf, fn_selfActions.sqf
- [x] Things from dayz_code -> actions. call_zombies.sqf, maintain_area.sqf, player_drink.sqf(?), player_eat.sqf(?), player_tagFriendly.sqf, player_wearClothes.sqf, trade_any_vehicle.sqf, trade_items.sqf(?). Prio:High
- [x] Things from dayz_code -> compile. fn_checkItems.sqf, fn_hasTools.sqf, fn_removeItems.sqf, object_removeTankTrap.sqf, player_antiWall.sqf, player_onPause.sqf(?), player_unlockDoor.sqf, player_updateGui.sqf, player_upgradeVehicle.sqf. Prio:High
- [x] Bags.hpp. Prio:High (Backpacks names)
- [x] Things from dayz_code -> Configs -> CfgWeapons -> Melee. Prio:Medium (Melee weapons names)
- [x] deathboards.hpp. Prio:low

~~Categories (Medical supplies, weapons categories) in Trader Menu~~ Due to database

~~ItemShovel.hpp~~ not used

~~MakerovSD.hpp(if possible) and maybe some other guns names(like "PKP Pecheneg", "Double-Barreled Shotgun"). Prio:Very low~~ Those are custom names (Proper names) or not worth breaking the class out into a new one to define the displayName.

**Comment by Adaptivity** [comment]
Can this be reopened? I want to work on this myself later when Epoch gets updated to new DayZ code.

**Comment by ebaydayz** [comment]
I would open a new issue, since this one is over two years old.

However, IMO it's not necessary to list all the things you translate. Anyone can see that by looking at stringtable.xml. For stuff that has been recently added you can look at the repo commit history or the history of the stringtable.xml file.

We generally won't merge anything that doesn't have localized strings going forward. However, the translations may be bad because they are done with Google Translate. In that case you can just check the history of stringtable.xml periodically and adjust any bad translations. I think most of the new DayZ Mod stuff we are going to merge already has stringtable entries.
