### ISSUE TITLE
Helicopter pook_H13: Server FPS drop

### ISSUE THREAD

**Issue by bleeding-** [EpochModTeam/DayZ-Epoch#969]
Spawned Bell 47/H-13 helicopter drops server FPS massively.

**With pook_H13**
2014/01/06, 19:11:47 "HIVE: Starting"
2014/01/06, 19:17:17 "DEBUG FPS : 12.7796 OBJECTS: 4595 : PLAYERS: 2"
2014/01/06, 19:18:17 "DEBUG FPS : 13.4567 OBJECTS: 4616 : PLAYERS: 2"
2014/01/06, 19:19:18 "DEBUG FPS : 13.5135 OBJECTS: 4623 : PLAYERS: 2"

**After delete pook_H13 from database**
2014/01/06, 20:42:41 "HIVE: Starting"
2014/01/06, 20:51:00 "DEBUG FPS : 49.3827 OBJECTS: 4553 : PLAYERS: 2"
2014/01/06, 20:52:00 "DEBUG FPS : 47.9042 OBJECTS: 4555 : PLAYERS: 2"
2014/01/06, 20:53:00 "DEBUG FPS : 49.3827 OBJECTS: 4564 : PLAYERS: 2"

**Comment by Markokil321** [comment]
I have removed my previous comments stating i could find no FPS drop while using these amphibious air vehicles.

I can confirm there is a server FPS impact when spawning in either of the amphibious cessna (Effects: GNT_C185E, GNT_C185F) or amphibious pook (Effects: pook_h13_amphib, pook_h13_amphib_...)
If a player enters an amphibious Cessna you will also notice a significant increase in out traffic right until the vehicle is deleted.

WITHOUT cessna (1 player ingame no ai): http://i.imgur.com/KWgxFbi.png
With amphibious cessna (1 player ingame no ai): http://i.imgur.com/YhWD7Xo.png

Same story regarding server FPS with amphibious pooks, but there was no increase in out traffic when using them

This only happens when using either amphibious pooks or amphibious cessnas, this does not happen when using regular pooks/cessnas or any other vehicle.

I am removing all these amphibious vehicles from our servers now :)
