### ISSUE TITLE
Stronger Zed type with adapted loot (IDEA)

### ISSUE THREAD

**Issue by FramedYannick** [EpochModTeam/DayZ-Epoch#977]
As many mods these days, maybe a stronger type of zombies can be implemented (think of bloodsuckers, docter Ivan,...) 
I allready have a working script that makes all police zombies stronger (need about 5 shots to the head, but easely changable) and drop a gold bar when killed.

If a new zombie class would be implemented, this would be a nice feature to implement to dayz epoch.
This script can also be used for different aplications:
giving soldier zombies more health for chest and head shots due to there armor and helmet.
police zombies wear bulletproof shirts.
worker zombies might have stronger legs due to protective clothing.
Just all ideas that are easely done with this script by just adding these lines everytime:

```
if (typeof _zed in ["z_policeman","zPolice_new_Base"]) then {_damMults=[0.0002,0.02,0.002,0.002,0.02];};
```

I'm happy to put my script in here if you guys are interested to implement this feature in epoch.

**Comment by ebayShopper** [comment]
This has been included since 1.6. All zeds with `_new_` in their class name (ViralZeds) have increased body armor:
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/Configs/CfgVehicles/Zeds/ViralZeds.hpp#L35

`z_soldier, z_soldier_pilot and z_soldier_heavy` also have increased armor:
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/Configs/CfgVehicles/Zeds/Zeds.hpp#L284

Further modifying damage handling or loot can be done via scripts if desired.
